### ISSUE TITLE
vAmiga and Amiga Enhanced Chip Set (ECS)

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/vAmiga#112]
Could ECS be implemented in the vAmiga?

3 option on Winuae:
1 ECS AGNUS
2 ECS DENISE
3 FULL ECS

Note:
Amigas produced from 1990 onwards featured a mix of OCS and ECS chips, such as later versions of the Amiga 500 and the Commodore CDTV. Other ECS models were the Amiga 500+ in 1991 and lastly the Amiga 600 in 1992.
Notable improvements were the Super Agnus and the HiRes Denise chips. The sound and floppy controller chip, Paula, remained unchanged from the OCS design. Super Agnus supports 2 MB of Chip RAM, whereas the original Agnus/Fat Agnus and subsequent Fatter Agnus can address 512 KB and 1 MB, respectively. The ECS Denise chip offers Productivity (640×480 non-interlaced) and SuperHiRes (1280×200 or 1280×256) display modes (also available in interlaced mode), which are however limited to only 4 on-screen colors. Essentially, a 35 ns pixel mode was added plus the ability to run arbitrary horizontal and vertical scan rates. This made other display modes possible, but only the aforementioned modes were supported originally out of the box. For example, the Linux Amiga framebuffer device driver allows the use of several other display modes. Other improvements were the ability of the blitter to copy regions larger than 1024×1024 pixels in one operation and the ability to display sprites in border regions (outside of any display window where bitplanes are shown). ECS also allows software switching between 60 Hz and 50 Hz video modes.

**Comment by dirkwhoffmann** [comment]
Hi Mortinus,

right now there are no plans to support ECS soon, because vAmiga is such an early development  state that it's better to narrow down compatibility requirements as much as possible. Once OCS support is stable (which will take a decent amount of time), it's possible to think about ECS support. 

BTW, ...

<img width="893" alt="Bildschirmfoto 2019-07-21 um 19 10 20" src="https://user-images.githubusercontent.com/12561945/61594344-3bc5e500-abeb-11e9-9444-1d4d8c9171dd.png">

**Comment by dirkwhoffmann** [comment]
I close this for now.
