### ISSUE TITLE
Turrican hangs before asking for disk two

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#125]
Turrican hangs before asking for disk two or does not show the message to switch disks.
[Turrican (1990)(Rainbow Arts)[cr PNA][h ECI][t +4 PNA](Disk 1 of 2).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3496008/Turrican.1990.Rainbow.Arts.cr.PNA.h.ECI.t.%2B4.PNA.Disk.1.of.2.adf.zip)

[Turrican (1990)(Rainbow Arts)[cr PNA][h ECI][t +4 PNA](Disk 2 of 2).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3496009/Turrican.1990.Rainbow.Arts.cr.PNA.h.ECI.t.%2B4.PNA.Disk.2.of.2.adf.zip)

**Comment by dirkwhoffmann** [comment]
Let's see... the game hangs in an infinite loop here: 

<img width="1028" alt="Bildschirmfoto 2019-08-13 um 16 39 05" src="https://user-images.githubusercontent.com/12561945/62951529-7128b180-bdea-11e9-8234-804d3d6d8ca3.png">

A4 points to the custom register set. The move statement copies the current vertical position to the background color register. This causes the color effect:

<img width="841" alt="Bildschirmfoto 2019-08-13 um 16 38 42" src="https://user-images.githubusercontent.com/12561945/62952395-db8e2180-bdeb-11e9-8b20-77f33b8b08b5.png">

"bra" is an unconditional branch. Hence, the Amiga could only break out of this loop via an interrupt. So let's check Paula...

<img width="980" alt="Bildschirmfoto 2019-08-13 um 16 53 29" src="https://user-images.githubusercontent.com/12561945/62951828-f3b17100-bdea-11e9-87a9-ae9f335654fc.png">

All interrupts are disabled which means that we cannot leave the infinite loop, no matter what. 

Here are the two possibilities I can think of: 

1) We reach this strange loop by one of the trillion remaining bugs in the emulator. 
2) The game makers send us into this infinite loop purposely, because the game is copy protected. 

By judging the symptom of the bug, 1) feels unlikely. On the other hand, 2) is also unlikely, because the game comes with some hacker intro 🤔.

**Comment by Alessandro1970** [comment]
Turrican on vAmiga is great now !!!

<img width="803" alt="Schermata 2019-09-01 alle 10 14 54" src="https://user-images.githubusercontent.com/34916641/64073666-6a7eb300-cca1-11e9-92e9-0ca4b0cb1901.png">

You can close

**Comment by dirkwhoffmann** [comment]
> You can close

I need to play it first 🤤

**Comment by Alessandro1970** [comment]
When game flashes in blu you have to change disk to load...

**Comment by dirkwhoffmann** [comment]
What did you do to run the game? I still get the Copper bars 🙁.

Did you use a particular HW config or Blitter level?

**Comment by dirkwhoffmann** [comment]
> When game flashes in blu you have to change disk to load...

Oh, I didn't read this, sorry 🙄

**Comment by dirkwhoffmann** [comment]
> When game flashes in blu you have to change disk to load...

You mean when it flashes like in the image at to top of this thread? I can't get it to run.

**Comment by Alessandro1970** [comment]
Turn the disk when a thunderbolt blue appears in the screen image...where appears stuck.

**Comment by Alessandro1970** [comment]
Kick 1.3

**Comment by dirkwhoffmann** [comment]
I still can't get past the Copper bar screen:

<img width="841" alt="Bildschirmfoto 2019-08-13 um 16 38 42" src="https://user-images.githubusercontent.com/12561945/62952395-db8e2180-bdeb-11e9-8b20-77f33b8b08b5.png">

> Turn the disk when a thunderbolt blue 

How does thunderbolt blue look like? 😩

**Comment by dirkwhoffmann** [comment]
In v0.38, it worked for me as well:

<img width="862" alt="Bildschirmfoto 2019-09-16 um 17 08 38" src="https://user-images.githubusercontent.com/12561945/64995070-4da0cd00-d8a8-11e9-9e4f-c16d62bcced1.png">


This is the hw config I was using: 

<img width="862" alt="Bildschirmfoto 2019-09-16 um 17 08 44" src="https://user-images.githubusercontent.com/12561945/64995112-67daab00-d8a8-11e9-8e4d-eb96f4f0f9e0.png">
