### ISSUE TITLE
Bermuda Project has mouse emulation incompatibility

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#133]
Press RMB to show the menù during the game, I cannot use no commands in the menù.
Selecting the "Options" gives no result, like other commands.
[Bermuda Project (1987)(MirrorSoft)[cr CCS].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511841/Bermuda.Project.1987.MirrorSoft.cr.CCS.adf.zip)
<img width="885" alt="Schermata 2019-08-17 alle 11 12 53" src="https://user-images.githubusercontent.com/34916641/63209377-4be4bd80-c0e0-11e9-9bbc-9f6488fc3617.png">

**Comment by dirkwhoffmann** [comment]
You need to connect a real two button mouse, because the game requires the user to press both mouse buttons together.

Here is how it works: 

Hold down right button:

<img width="339" alt="Bildschirmfoto 2019-09-02 um 11 22 58" src="https://user-images.githubusercontent.com/12561945/64104336-5952a680-cd74-11e9-833a-1931c1330cac.png">

Click left button: 

<img width="339" alt="Bildschirmfoto 2019-09-02 um 11 23 14" src="https://user-images.githubusercontent.com/12561945/64104348-5fe11e00-cd74-11e9-83b1-264c65b99c3a.png">

Click left button again: 

<img width="339" alt="Bildschirmfoto 2019-09-02 um 11 23 23" src="https://user-images.githubusercontent.com/12561945/64104365-653e6880-cd74-11e9-90b2-51e5ab141b81.png">

**Comment by Alessandro1970** [comment]
No magic mouse ?
...or a key on keyboard can be configurated to work as a mouse button ?

**Comment by dirkwhoffmann** [comment]
> No magic mouse ?

I am unsure if both buttons can be pressed on the Magic Mouse. 

> ...or a key on keyboard can be configurated to work as a mouse button ?

This can't be integrated in the current architecture. It would require to assign a device *and* a keyset to a control port, but everything in vAmiga has been designed to assign a device *or* a keyset to a control port. 

Maybe there are tricks to press both buttons on the Magic Mouse. This would be the best solution.

**Comment by Alessandro1970** [comment]
On Amiga the keys Amiga+rLeftAlt gives as result the LMB click ...don’t remember
