### ISSUE TITLE
Flashback hangs after press "Start"

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#134]
Flashback hangs after press start in the main menù:
[FBack1.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511876/FBack1.adf.zip)
[FBack2.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511878/FBack2.adf.zip)
[FBack3.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511879/FBack3.adf.zip)
[FBack4.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511880/FBack4.adf.zip)
<img width="887" alt="Schermata 2019-08-17 alle 11 50 57" src="https://user-images.githubusercontent.com/34916641/63209762-a59bb680-c0e5-11e9-9174-3e73743f856b.png">

**Comment by dirkwhoffmann** [comment]
In my first attempt, I didn't reach the title image screen (which is displayed above). When I configured df0: as an original drive (1 x speed, was a turbo drive before), it worked. 

The real issue was presumably the disk change bug that has been fixed recently: 

😎
<img width="840" alt="Bildschirmfoto 2019-09-02 um 11 35 11" src="https://user-images.githubusercontent.com/12561945/64105184-ff52e080-cd75-11e9-9ef1-42120772e00b.png">

BTW, is there a way to launch the game faster? There seems to be no way to skip the introductory video...

<img width="806" alt="Bildschirmfoto 2019-09-02 um 11 29 58" src="https://user-images.githubusercontent.com/12561945/64105286-3a551400-cd76-11e9-842d-a6b291fdb02c.png">
