### ISSUE TITLE
Alien Breed: Cannot see the main character

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#135]
The main character is invisible.

<img width="886" alt="Schermata 2019-08-17 alle 11 55 15" src="https://user-images.githubusercontent.com/34916641/63209858-90735780-c0e6-11e9-81d9-7be8a8fec6d1.png">

[ABreed1.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511887/ABreed1.adf.zip)
[ABreed2.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3511888/ABreed2.adf.zip)

**Comment by Alessandro1970** [comment]
With v3 the games hangs and does not load after inserting disk2; instead if you put disk2 in df1 the game now crashes:

[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3563171/CRASH.TXT)

**Comment by dirkwhoffmann** [comment]
CRASH.TXT

`Assertion failed: (!hasDisk()), function insertDisk, file Drive.cpp, line 486.`

🤭 My new code is pushing two disks in a single drive. Good that it's not real hardware.

**Comment by dirkwhoffmann** [comment]
I can reproduce the invisibility of the main character.

We should try to find out if the main character is drawn as a sprite (maybe in another emulator with sprite drawing disabled if such an options exists). 

vAmiga's DMA debugger shows that there is no sprite DMA going on. Of course, there is also the possibility that the main character is drawn by the Blitter.  

<img width="840" alt="Bildschirmfoto 2019-09-02 um 11 47 37" src="https://user-images.githubusercontent.com/12561945/64106114-d59ab900-cd77-11e9-8f82-a1b9250326ee.png">

**Comment by dirkwhoffmann** [comment]
The game has a strange Copper list. E.g., it uses masked Waits which don't make sense for me here:

<img width="980" alt="Bildschirmfoto 2019-10-16 um 17 15 31" src="https://user-images.githubusercontent.com/12561945/66933441-63d1b280-f039-11e9-9086-a634ee20d2cf.png">

It also writes to sprite registers manually, but no sprites are visible in vAmiga. This is surprising, because I was pretty confident that the current sprite implementation is correct.

**Comment by mithrendal** [comment]
I have played the game once in [iAmiga](https://github.com/emufreak/iAmiga). It was quite nice. The best thing was the simultanously multiplayer which I implemented in iAmiga with apples multi peer connectivity Framework. Me and a friend played AlienBreed on our iPhones. Should definitly work then in WinUAE.

**Comment by dirkwhoffmann** [comment]
Having a main character now makes this game one of my favourites 😎.

<img width="866" alt="Bildschirmfoto 2019-10-20 um 17 58 05" src="https://user-images.githubusercontent.com/12561945/67162336-47988300-f363-11e9-9f24-ff8cf731caa4.png">

**Comment by dirkwhoffmann** [comment]
> The best thing was the simultanously multiplayer which I implemented in iAmiga

<img width="314" alt="Bildschirmfoto 2019-10-20 um 18 02 02" src="https://user-images.githubusercontent.com/12561945/67162402-08b6fd00-f364-11e9-9f67-a558d292bad3.png">

👍👍👍

It is my understanding that iAmiga is an UAE clone for the iPhone. Is this true? 🤔

But how is the AppStore problem solved? Does Apple allow emulators (i.e. those that come without Roms by default)?

**Comment by dirkwhoffmann** [comment]
Any suggestions 😬?

<img width="981" alt="Bildschirmfoto 2019-10-20 um 18 26 31" src="https://user-images.githubusercontent.com/12561945/67162745-731d6c80-f367-11e9-9df1-2f18c5ebffef.png">

**Comment by mithrendal** [comment]
> It is my understanding that iAmiga is an UAE clone for the iPhone. Is this true? 🤔

Yes it is a clone o a very early UAE version made for a game console do not remember which. Some guys made it runnable on iPhone. But it was missing hires modes, because it the target game console could only handle 320x200. So I fixed that. Wanted to see a full glory workbench on my iPhone.😍 That was fun.

> But how is the AppStore problem solved? Does Apple allow emulators (i.e. those that come without Roms by default)?

No I think they do not allow it. For me and my friends it was meant only for side loading. You could back(2016?) then sideload with a free provisioning cert with a duration of 3 months. But somewhere in the past (2017?) apple changed it to 7 days. When I today deploy to iPhone it will only last 7 days until it gets broken. That honestly destroyed all the fun we put into it. So by now the iAmiga project is fairly abandoned.  💀 But if you like you can deploy it on your iPhone just for the fact to see workbench on it and to let it speak "I am an amiga". 😜

**Comment by dirkwhoffmann** [comment]
I ❤️ AAVSS technology (TM)

> That honestly destroyed all the fun we put into it.

I understand that. Apple is so strict about their AppStore policies that I will most likely never develop an iPhone app. They can ruin your work by pulling the plug any time.

>  and will rescues you out of a hopeless situation like this

Too late, nobody came 😢. In total desperation I tried to escape by disabling sprite drawing in the debug menu. This made me invisible, but the game does not use collision checking. At least I was completely digested after a few seconds and didn't have to suffer long. So sad 🤧.
