### ISSUE TITLE
Syncro Express and Cyclone 2 are broken

### ISSUE THREAD

**Issue by KenDFish** [dirkwhoffmann/vAmiga#159]
Trying a few of my very old ADFs, which originated from my own floppies, I've stumbled across "Synchro Express" (which I vaguely remember was a copy utility, which relied on a small piece of hardware connected to the floppy port which aimed to allow the duplication of copy-protected disks). However, it crashes almost instantly after reading the boot block. The error is

`Assertion failed: (!hasEvent<REG_CPU_SLOT2>()), function scheduleRegEvent, file /Users/hoff/vAmiga/Amiga/Computer/Agnus/EventHandler.cpp, line 966.`

[KD0006 Synchro Express.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3581186/KD0006.Synchro.Express.adf.zip)

**Comment by dirkwhoffmann** [comment]
With my latest refactoring efforts, I was able to get rid of the REG_xxx_SLOTs completely. I've replaced them by a brand new, cutting edge technology called "Agnus action flags" 😎.

This seems to solve the crashing problem: 

<img width="862" alt="Bildschirmfoto 2019-09-06 um 18 49 24" src="https://user-images.githubusercontent.com/12561945/64445752-7a4e2b00-d0d7-11e9-8832-f90434c257d4.png">

The copy program itself doesn't work. It's analysing drive speed for minutes now 😮.

The copy programs are really good test cases, because they address the drive on the hardware level and not through trackdisk device. If the copy programs work in SAE, I can compare all register accesses and see what's going wrong.

Here is how Syncro Express looks like:

<img width="862" alt="Bildschirmfoto 2019-09-06 um 18 58 07" src="https://user-images.githubusercontent.com/12561945/64446155-5d662780-d0d8-11e9-9306-e46f34a68ff9.png">

It asks me to remove the printer cable. I didn't know I emulate such a thing 😳.

**Comment by mithrendal** [comment]
I love Agnus action flags .... 😎

**Comment by dirkwhoffmann** [comment]
> I love Agnus action flags ....
 
No, you don't,  action flags are 🤮. Apparently the developer did not consider the case that Agnus and the CPU can both write to a register at the "same time" 🙄. Since their emulated clocks can be out-of-sync for many cycles, action flags simply don’t work.

I think I have to fire the developer, because fixing this requires a broader architectural change  😖.
 
Anyway, new technology is around the corner: The „register change recorder“ 😎. Hot stuff. The only problem: Not a single line has been implemented, yet 😢 . But I already know that it has to be a ring-buffer based design . Stay tuned...

**Comment by mithrendal** [comment]
I love "register change recorder" 😃

**Comment by dirkwhoffmann** [comment]
Cyclone 2 issue seems to be fixed. vAmiga complains about the missing hardware adapter and so does UAE:

<img width="720" alt="Bildschirmfoto 2020-03-20 um 18 34 52" src="https://user-images.githubusercontent.com/12561945/77190777-2686ba80-6ada-11ea-8cba-d27346bd7e72.png">

<img width="990" alt="Bildschirmfoto 2020-03-20 um 18 36 22" src="https://user-images.githubusercontent.com/12561945/77190781-28507e00-6ada-11ea-83bf-1fe9e23abbf8.png">
