### ISSUE TITLE
Agony hangs after intro

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#166]
Agony hangs after intro and there is probably a graphic bug in the intro screen.

<img width="807" alt="Schermata 2019-09-21 alle 09 29 34" src="https://user-images.githubusercontent.com/34916641/65369861-f9546f00-dc52-11e9-8029-a6657d7e6c6c.png">

[Agony (1992)(Psygnosis)[cr CSL][t +5 Thunderloop](Disk 1 of 3).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3638432/Agony.1992.Psygnosis.cr.CSL.t.%2B5.Thunderloop.Disk.1.of.3.adf.zip)
[Agony (1992)(Psygnosis)[cr CSL][t +5 Thunderloop](Disk 2 of 3).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3638433/Agony.1992.Psygnosis.cr.CSL.t.%2B5.Thunderloop.Disk.2.of.3.adf.zip)
[Agony (1992)(Psygnosis)[cr CSL][t +5 Thunderloop](Disk 3 of 3).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3638435/Agony.1992.Psygnosis.cr.CSL.t.%2B5.Thunderloop.Disk.3.of.3.adf.zip)

**Comment by dirkwhoffmann** [comment]
I was able to load it with the following compatibility settings:

<img width="643" alt="Bildschirmfoto 2019-09-21 um 17 50 04" src="https://user-images.githubusercontent.com/12561945/65379585-650cfb00-dc98-11e9-8c5c-719e7ab65ff2.png">

<img width="862" alt="Bildschirmfoto 2019-09-21 um 17 48 05" src="https://user-images.githubusercontent.com/12561945/65379586-6b02dc00-dc98-11e9-8dda-f0208f6bd525.png">

It hang when Blitter accuracy was set to level 0 (fast Blitter).

**Comment by dirkwhoffmann** [comment]
The graphics bug is actually artwork 🥺:

<img width="766" alt="Bildschirmfoto 2019-09-22 um 18 38 40" src="https://user-images.githubusercontent.com/12561945/65395401-542bba80-dd68-11e9-854d-2bd6fd8598ab.png">

However, I did experience the "hanging" issue today. After the intro screen (the one with the buggy artwork), it didn't continue. Maybe there is some indeterministic issue somewhere (because it worked yesterday).

My gut tells me that we should come back to this issue only after the already known disk drive issues have been ruled out.

**Comment by Alessandro1970** [comment]
In WinUAE too...

![Untitled 3](https://user-images.githubusercontent.com/34916641/65425117-87745500-de0d-11e9-87b1-d2647cf2c11b.png)


...Can Close...

**Comment by Alessandro1970** [comment]
...in WinUAE it does not flicker !?

![Untitled 6](https://user-images.githubusercontent.com/34916641/65425157-a1159c80-de0d-11e9-877d-9fb054852849.png)

**Comment by dirkwhoffmann** [comment]
> ...in WinUAE it does not flicker !?

This is probably the same flickering issue as the one in R-Type II. We need to check the Copper list when this image is displayed.

**Comment by dirkwhoffmann** [comment]
> ...in WinUAE it does not flicker !?

I just looked at the flickering issue. It's not a bug, it's a feature 😎. 

It flickers, because the logo is drawn in interlace mode. Flicker emulation can be customised in the Video settings. You can either disable it or change it's intensity.

<img width="644" alt="Bildschirmfoto 2019-09-26 um 08 57 54" src="https://user-images.githubusercontent.com/12561945/65665557-1e265900-e03c-11e9-8547-9020f27d48e0.png">
