### ISSUE TITLE
Heimdall 2 memory error

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#213]
I loaded this game with kick 1.2 and with kick 1.3, with 512k ram slow and without but there is this strange memory error message:

<img width="801" alt="Schermata 2019-10-27 alle 10 14 12" src="https://user-images.githubusercontent.com/34916641/67632426-663ad480-f8a3-11e9-8d52-d2c63874d3fe.png">

Game stored here:
[Archivio 3.zip](https://github.com/dirkwhoffmann/vAmiga/files/3775673/Archivio.3.zip)

**Comment by dirkwhoffmann** [comment]
Just checked with UAE. It's not a bug. The game needs 1 MB Chip Ram which is not supported by vAmiga at the moment.

**Comment by mithrendal** [comment]
Alessandro you should be able to play it on your A2000. 🤗

Because according to your picture it had 1MB Chipram, when your A2000 was at the repairshop.

![grafik](https://user-images.githubusercontent.com/17108995/67639843-23a1e800-f8f5-11e9-8066-49221c70f995.png)

also I found a documentation, how to enable 1MB chipram in a A500. As I understood it is also possible for a A500 that its ordinary trapdoor 512 KB expansion may serve as chipram. Of course the Aguns 8372A is mandatory for this change. It also describes that allessandros revision 6 of the A2000 had 1MB chipram right from the factory.

Here is the description: http://amiga.resource.cx/manual/1MBChip_A500_A2000.pdf

**Comment by dirkwhoffmann** [comment]
>  it had 1MB Chipram, when your A2000 was at the repairshop.

🤤🤤🤤

**Comment by dirkwhoffmann** [comment]
> Of course the Aguns 8372A is mandatory for this change

My whole armada of A500's has the 8372A on board (I think). Hence, we can definitely support 1 MB Chip Ram later, once vAmiga has become more stable. Maybe for a v2.x release or so. Right now, I would be happy to reach v0.9 (public beta quality kind of) at some point in time.

**Comment by Alessandro1970** [comment]
My A2000 at the moment is unusable...
But I owned tha game and I finished it on my 2000.
Yes my Amiga has 1mb chip ram soldered on mobo and ECS.
Also A500 plus should have the ECS and 1mb chip ram.
I think that vAmiga should have the ECS ( ...and the 68010-68881 ;) )
