### ISSUE TITLE
Leatherneck Blitter bug

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#217]
This games has blitter bugs in blitter accuracy 1,2 and 3.
[LeatherNeck.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3797115/LeatherNeck.adf.zip)

<img width="884" alt="Schermata 2019-11-01 alle 09 11 26" src="https://user-images.githubusercontent.com/34916641/68011545-e1c3c980-fc87-11e9-9149-41bc7f0c5604.png">

**Comment by dirkwhoffmann** [comment]
It works if Blitter runs at level 0 right from the beginning. 

There is at least one big Blitter timing bug left in vAmiga. I think bus cycle sharing is completely wrong if the BLTPRIO bit set to false.

Besides: This game is totally unfair: 15 to 1 🤨.

<img width="818" alt="Bildschirmfoto 2019-11-01 um 15 33 05" src="https://user-images.githubusercontent.com/12561945/68032165-6bda5500-fcbd-11e9-9241-0433d11e7a18.png">

**Comment by dirkwhoffmann** [comment]
In theory, it works in v0.49 in Blitter mode 2. In practice, it stops at address $5002E, because of a hard-coded breakpoint which I forgot to remove 🤭. Luckily, the breakpoint can be deleted manually in the CPU inspector by clicking on the stop-sign icon.

<img width="980" alt="Bildschirmfoto 2019-12-02 um 15 51 19" src="https://user-images.githubusercontent.com/12561945/69968949-c4e71400-151b-11ea-8cb4-ceac4735893d.png">
