### ISSUE TITLE
Exolon first intro does not work

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#221]
Exolon first intro does not work:
<img width="789" alt="Schermata 2019-11-03 alle 11 31 39" src="https://user-images.githubusercontent.com/34916641/68083817-ce526300-fe2d-11e9-86e7-b30f70bfbef7.png">

[Exolon (1989)(Hewson)[cr QTX][t +3 Cosmos].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3801445/Exolon.1989.Hewson.cr.QTX.t.%2B3.Cosmos.adf.zip)

**Comment by dirkwhoffmann** [comment]
Interesting test case. X-ray examination of this patient reveals nothing unusual so far:

<img width="774" alt="Bildschirmfoto 2019-11-03 um 18 26 33" src="https://user-images.githubusercontent.com/12561945/68089375-8866c080-fe68-11e9-94c0-524a4406c221.png">
<img width="389" alt="Bildschirmfoto 2019-11-03 um 18 28 41" src="https://user-images.githubusercontent.com/12561945/68089378-8b61b100-fe68-11e9-9335-3acce9b0052f.png">
<img width="375" alt="Bildschirmfoto 2019-11-03 um 18 30 02" src="https://user-images.githubusercontent.com/12561945/68089381-8dc40b00-fe68-11e9-913b-4fce2b728074.png">
<img width="375" alt="Bildschirmfoto 2019-11-03 um 18 30 26" src="https://user-images.githubusercontent.com/12561945/68089384-8f8dce80-fe68-11e9-9c24-2f134d8f8a89.png">

This is how it is supposed to look: 

<img width="734" alt="Bildschirmfoto 2019-11-03 um 18 33 07" src="https://user-images.githubusercontent.com/12561945/68089388-9a486380-fe68-11e9-94c0-180a2949bbf3.png">

TODO: Write a test case checking the DDF values of this game in hires mode, together with the horizontal shift value from BPLCON1.

**Comment by dirkwhoffmann** [comment]
I did some closer investigations today. As can be seen in the Copper list, the failing intro uses a DDFSTOP value of $D2. I’ve written a DDF test that checks the combinations around this value (Test Agnus/DDFNEW/farright1). Here are the results:

Amiga 500 8A: 🥰

![farright1_A500_8A](https://user-images.githubusercontent.com/12561945/73593470-1b190900-4505-11ea-9e23-fe15bd1fae6a.JPG)

UAE: 🤭

<img width="720" alt="farright1_uae" src="https://user-images.githubusercontent.com/12561945/73593473-21a78080-4505-11ea-9d30-abc421516418.png">

In the UAE image, I’ve marked the line with DDFSTOP = D2. Interestingly, this line is different on the real machine.

Since vAmiga passes test farright1, I’ve tried to run Exolon on the real machine and I got this: 😲

![IMG_2424](https://user-images.githubusercontent.com/12561945/73593519-87940800-4505-11ea-9349-cad9062971f4.jpeg)

Now there are two possibilities: 

- It’s a bug in UAE and the demo writer did not implement the intro on the real machine, but in UAE.

- The DDFSTRT / DDFSTOP window depends on the Agnus revision (one standard revision and another one with a build-in Klingon translator). To find out, we can either run Exolon on the A1000 or we can ask Toni who knows everything about Agnus revisions 😃.

**Comment by tonioni** [comment]
It is most common OCS/ECS Agnus compatibility problem. ECS Agnus has bit 1 in DDFSTRT/STOP. OCS does not. Some programs accidentally set it.

**Comment by dirkwhoffmann** [comment]
> ECS Agnus has bit 1 in DDFSTRT/STOP

Ah, OK, got it. Thanks a lot!! I always forget that my A500 has an ECS Agnus on board. When I select ECS Agnus in UAE, it matches my machine: 👍

<img width="720" alt="Bildschirmfoto 2020-02-01 um 15 58 40" src="https://user-images.githubusercontent.com/12561945/73594162-e9577080-450b-11ea-9eef-07ab76a4f2cc.png">

**Comment by dirkwhoffmann** [comment]
vAmiga now handles DDFSTART / DDFSTOP correctly for both OCS and ECS Agnus revisions.

<img width="910" alt="Bildschirmfoto 2020-02-02 um 10 32 42" src="https://user-images.githubusercontent.com/12561945/73606309-2e7db000-45a9-11ea-8530-8b6af774267d.png">

With the knowledge about the missing bit in the OCS revision, the fix was easy. The game itself is damn difficult though. I never managed to survive more than 20 seconds 😳.

<img width="910" alt="Bildschirmfoto 2020-02-01 um 21 32 24" src="https://user-images.githubusercontent.com/12561945/73606253-badba300-45a8-11ea-8444-8fafb23e39d8.png">
