### ISSUE TITLE
New test suite Interrupts/vblank

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#276]
>  00 00 13 35 CDR Roger. ... If any object goes too close and enters the black hole's point of no return, called the event horizon

This is a call for star commander Mithrendal. There are new tests in the vAmigaTS repo checking the effect of the raster beam crossing the event horizon (aka VERTB). 

Here is what Interrupts/vblank1 and and Interrupts/vblank3 look like on the A500 MMSE: 

![vblank1_A500_8A](https://user-images.githubusercontent.com/12561945/73465766-26dbc280-4381-11ea-8ff5-6f7f33938ff9.JPG)

![vblank3_A500_8AJPG](https://user-images.githubusercontent.com/12561945/73465791-30652a80-4381-11ea-9b33-ce90e4ebbe3b.JPG)

According to the A1000's build-in space-time-crack (aka VERTB delay), all 6 tests should look different on the A1000. Needs verification... 🤤

**Comment by mithrendal** [comment]
This is star commander Mithrendal 👮roger and over... I can hear your voice clear and loud...  
Just setting up archaic A1000 space vessel for a testdrive into the outer riffs of the solar system .... After driving all engines up (well only one😬) and 130% over the limit ... Oh hang on,...  there are  some strange vibration out of the engine room ...  strange noise turns out to come from rusty old engine drive df0: getting stuck on an used up floppy disk gear.... 

...Now I see them, yep.. I can clearly see some pictures coming in....

Wow, I can see the difference in vblank3 ... is this from the build-in space-time-crack  as toni reported ? 

![vblank1](https://user-images.githubusercontent.com/17108995/73490351-9ca95380-43ac-11ea-94b8-ec1e43449c1b.JPG)

![vblank2](https://user-images.githubusercontent.com/17108995/73490399-bc407c00-43ac-11ea-853a-973525c2c178.JPG)

![vblank3](https://user-images.githubusercontent.com/17108995/73490406-c2cef380-43ac-11ea-84fd-e6f702326392.JPG)

![vblank4](https://user-images.githubusercontent.com/17108995/73490421-cbbfc500-43ac-11ea-8738-81c44e40453f.JPG)

![vblank5](https://user-images.githubusercontent.com/17108995/73490437-d4b09680-43ac-11ea-92ca-adfc7d04fc71.JPG)

![vblank6](https://user-images.githubusercontent.com/17108995/73490455-de39fe80-43ac-11ea-8ada-a288c2a68c2e.JPG)

**Comment by dirkwhoffmann** [comment]
Analyzing result ... 
🤓
processing ... 
🧐
processing ... 
😳
processing ... 
😶
processing ... 
🤭
processing ...
🤩

Confirmed: When the raster beam crosses the event horizon, old Agnus experiences a time dilation of 1 scanline:

<img width="977" alt="Bildschirmfoto 2020-01-30 um 22 19 51" src="https://user-images.githubusercontent.com/12561945/73492164-72599500-43b0-11ea-9511-c0db2ea31c02.png">

That's pretty cool. In future vAmiga can do something different depending on the selected Agnus model.

**Comment by dirkwhoffmann** [comment]
A1000 pictures are now part of the test repo. Furthermore, VERTB timing is now good in vAmiga 😎.

vblank3 in A500 / A2000 mode: 

<img width="910" alt="Bildschirmfoto 2020-01-31 um 08 58 48" src="https://user-images.githubusercontent.com/12561945/73522283-4964ee80-4408-11ea-9209-97615f61e4ee.png">

vblank3 in A1000 mode:

<img width="910" alt="Bildschirmfoto 2020-01-31 um 08 59 35" src="https://user-images.githubusercontent.com/12561945/73522296-52ee5680-4408-11ea-927b-94ab7295733b.png">

Some of the tests still have issues, i.e., those that keep the Copper running all the time. vAmiga doesn't handle the Copper start sequence correctly which is issued when the Copper strobe register is written to at the beginning of each frame. This is the next thing I'll look into...

BTW, there is a new review on Youtube about vAmiga's current emulation accuracy 😳.

https://www.youtube.com/watch?v=XIAbbZJPAJA
