### ISSUE TITLE
Support 84 tracks

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#290]
In UAE, I can step up to cylinder 83 (which means 84 cylinders in total).

<img width="719" alt="Bildschirmfoto 2020-02-21 um 17 12 42" src="https://user-images.githubusercontent.com/12561945/75051813-df071180-54ce-11ea-9329-834f240a1cb2.png">

In vAmiga, I can only step up to cyclinder 79 🙈.

I am wondering how an uninitialised track looks like when read by the Amiga hardware. Does the Amiga read zeros everywhere or arbitrary garbage? 🤔

**Comment by dirkwhoffmann** [comment]
I found this in SAE:

```
tword = (tword << 1) >>> 0;
if (!drive_empty(drv)) {
    if (unformatted(drv))
        tword = (tword | ((Math.decimalRandom() & 0x1000) ? 1 : 0)) >>> 0;
    else
        tword = (tword | getonebit(drv.bigmfmbuf, mfmpos)) >>> 0;
    }
```

> Does the Amiga read zeros everywhere or arbitrary garbage?

Hence, the answer is: garbage

**Comment by tonioni** [comment]
Yeah, those tracks are almost always unformatted on real floppies.

I think there was some bad loader (don't remember) that accidentally attempted to read from track 80 and would hung waiting for sync word and only worked because track is unformatted. Sync word will be found sooner or later and loading succeeded because it didn't care about checksums and didn't need the data...
