### ISSUE TITLE
Sword of Sodan graphics errors

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#30]
vAmiga hangs as soon as this disc is inserted, but the disk works with other emulators.
I tried with or without sloram etc. but the incompatibility starts as soon as this disc is inserted.
It looks like nothing is loaded, either it's a format problem or something in the bootblock.
Insert in DF0: do not load from WB.

Report: 
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3220103/report.txt)

Adf:

[Simple text_test.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3220106/Simple.text_test.adf.zip)

**Comment by dirkwhoffmann** [comment]
You did run into an intentional crash in function pokeDSKSYNC:

    void
    DiskController::pokeDSKSYNC(uint16_t value)
    {
        assert(false);
        debug(DSK_DEBUG, "pokeDSKSYNC(%X)\n", value);
        dsksync = value;
    }

The DSKSYNC register is not implemented properly yet. Because of this, I decided to let the emulator crash (doing so let's me collect test-cases using this register). I'll get back to this when DSKSYNC has been implemented.

**Comment by dirkwhoffmann** [comment]
Fixed in http://www.dirkwhoffmann.de/vAmiga/vAmiga_0.23.zip

<img width="916" alt="Screenshot 2019-06-05 at 08 51 45" src="https://user-images.githubusercontent.com/12561945/58936888-1f700500-8771-11e9-86d7-bec626f0423b.png">

**Comment by Alessandro1970** [comment]
If I insert Sword of Sodan disk 1 it hangs:
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3258943/report.txt)

[Sword of Sodan (1989)(Discovery Software)[cr MFC][t +2 MFC](Disk 1 of 4).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3258947/Sword.of.Sodan.1989.Discovery.Software.cr.MFC.t.%2B2.MFC.Disk.1.of.4.adf.zip)

**Comment by dirkwhoffmann** [comment]
for (int i = currentPixel; i < 2 * agnus->diwHstop; i++) {
            assert(i < sizeof(rasterline));
            rasterline[i] = openR;
        }

😯 This game writes an unusually high value into DIWSTOP (right side of display window). I'll look into it ...

**Comment by dirkwhoffmann** [comment]
No more write accesses outside the visible screen area 😃:

<img width="1032" alt="Screenshot 2019-06-06 at 17 01 50" src="https://user-images.githubusercontent.com/12561945/59043791-326ffb80-887d-11e9-9fc8-fc1290c330e3.png">

Yeeeeeeessssss, I remember that one. Horizontal scrolling at it's best 😎:

<img width="1032" alt="Screenshot 2019-06-06 at 17 02 18" src="https://user-images.githubusercontent.com/12561945/59043749-1ec49500-887d-11e9-8e82-903daff4618a.png">

Oh no... 🙈

<img width="1032" alt="Screenshot 2019-06-06 at 17 02 34" src="https://user-images.githubusercontent.com/12561945/59043730-15d3c380-887d-11e9-8d0f-b2d7de3d8d41.png">

**Comment by Alessandro1970** [comment]
With release 0.29 the intro menu is not more visible:
<img width="890" alt="Schermata 2019-07-18 alle 00 29 23" src="https://user-images.githubusercontent.com/34916641/61416303-8269c580-a8f3-11e9-908a-794d66b6d451.png">

**Comment by Alessandro1970** [comment]
...the game starts pressing some Fx keys but there are some graphic errors in the upper left corner:

<img width="878" alt="Schermata 2019-07-18 alle 00 34 17" src="https://user-images.githubusercontent.com/34916641/61416425-f2784b80-a8f3-11e9-96f5-64d17dad9e51.png">

**Comment by dirkwhoffmann** [comment]
Intro screen got broken by commit b18a277 (July 1st)

**Comment by dirkwhoffmann** [comment]
Intro is good again 😎.

<img width="858" alt="Bildschirmfoto 2019-08-08 um 12 55 36" src="https://user-images.githubusercontent.com/12561945/62698127-a7c28e80-b9dc-11e9-9d91-53eb1c875fa6.png">

When the intro screen comes up, DIWSTRT and DIWSTOP are set to unusual coordinates ($00 and $FF, respectively) and trigger an "out of bounds" condition in vAmiga. Removing the check solves the issue. However, I think that I added the bound check because some vAmigaTS test was failing without the check. I need to doublecheck all DIW related test cases and probably write more of them.

The game itself seems to work fine now: 

<img width="858" alt="Bildschirmfoto 2019-08-08 um 12 51 09" src="https://user-images.githubusercontent.com/12561945/62697968-3e428000-b9dc-11e9-8c8b-cb01497010b8.png">

A little bit bloody though 😬

<img width="858" alt="Bildschirmfoto 2019-08-08 um 12 52 14" src="https://user-images.githubusercontent.com/12561945/62697989-4dc1c900-b9dc-11e9-8a6f-b6db9a9d357c.png">

Anyway, let's see what comes next 🤔

<img width="858" alt="Bildschirmfoto 2019-08-08 um 12 52 50" src="https://user-images.githubusercontent.com/12561945/62698012-5e723f00-b9dc-11e9-8663-89f76f688ec1.png">

Oooups 🙄

<img width="858" alt="Bildschirmfoto 2019-08-08 um 12 53 08" src="https://user-images.githubusercontent.com/12561945/62698022-692cd400-b9dc-11e9-86eb-8295b790ed22.png">

Hmmm, all games I tested so fa  seem to have gotten more difficult over time. Probably some kind of mysterious ageing issue with ADF files? 🤔

**Comment by Alessandro1970** [comment]
Could you let us to download a the new beta telease ?

**Comment by dirkwhoffmann** [comment]
> Could you let us to download a the new beta telease ?

Coming soon. I want to walk through all existing vAmigaTS tests first. To implement display hierarchy (sprites before or behind playfields), I had to overhaul the complete graphics backend. Unfortunately, this has broken some existing functionality.

BTW, did you get back the recapped A2000 mainboard yet?

**Comment by Alessandro1970** [comment]
I have sent my A2000 MoBo to a repair center...
At the moment they have not told me anything.
I have to wait...

**Comment by dirkwhoffmann** [comment]
Findings: 

DIW settings in the intro: 

    [1070] ( 12, 24)  0601A8 BCB-D- 606C 0000 [074014] Agnus: pokeDIWSTRT<Copper>(2801)
    [1070] ( 12, 26)  0601A8 BCB-D- 606C 0000 Agnus: setDIWSTRT(2801)
    [1070] ( 12, 26)  0601A8 BCB-D- 606C 0000 Agnus: newDiwVstrt = 40 newDiwHstrt = 1
    [1070] ( 12, 26)  0601A8 BCB-D- 606C 0000 Agnus: newDiwHstrt is too small
    [1070] ( 12, 28)  0601A8 BCB-D- 606C 0000 [074018] Agnus: pokeDIWSTOP<Copper>(30FF)
    [1070] ( 12, 30)  0601A2 BCB-D- 606C 0000 Agnus: setDIWSTOP(30FF)
    [1070] ( 12, 30)  0601A2 BCB-D- 606C 0000 Agnus: newDiwVstop = 304 newDiwHstop = 511
    [1070] ( 12, 30)  0601A2 BCB-D- 606C 0000 Agnus: newDiwHstop is too large

According to my model, only the bg color can be drawn. Indeed, when the particular values for DIWSTART and DIWSTOP are replicated in a test case, the screen remains black in SAE (as predicted by the model).

TODO: Check other parameters such as the  DDF settings and replicate them in the test case.

**Comment by dirkwhoffmann** [comment]
Added tests diw9, diw10, diw11 to vAmigaTS repo.

The three tests provide strong evidence for my hypothesis that the DIW H flip-flop is automatically set at the beginning of each frame. I am pretty sure this fixes the Sword of Sodan intro bug. We'll see once it's implemented...

**Comment by dirkwhoffmann** [comment]
Fixed in V0.32
