### ISSUE TITLE
What happened to DF1(0.68)?

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#308]
What happened to DF1(0.68)?

**Comment by dirkwhoffmann** [comment]
As a result of reworking the preferences panel, all internal user default keys have been renamed. Hence, vAmiga starts with the default settings, because it cannot find any matching key in the user defaults storage on disk. You need to reenable the external drives in the hardware settings: 

<img width="285" alt="Bildschirmfoto 2020-04-20 um 07 00 52" src="https://user-images.githubusercontent.com/12561945/79715716-c0f23d80-82d4-11ea-8dbb-cb18f20b7d4e.png">

There is another change. Configuration changes are no longer saved automatically in the user defaults storage on disk (because it causes weird behavior when working with multiple emulator instances in parallel). You need to manually click "Use as default" to let vAmiga use these settings the next time you start the emulator.

<img width="641" alt="Bildschirmfoto 2020-04-20 um 07 07 07" src="https://user-images.githubusercontent.com/12561945/79715997-994fa500-82d5-11ea-8d0b-f87c59376a5e.png">
