### ISSUE TITLE
Crash with Beach Volley (1989)

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#317]
After the logo "Ocean" appears vAmiga goes crazy and crashes totally!

<img width="912" alt="Ocean" src="https://user-images.githubusercontent.com/45571833/80424924-f86b7600-88e2-11ea-9a7d-e2e60c7a5e0a.png">

We can go to the beach with SAE (London??🤔):

![beach](https://user-images.githubusercontent.com/45571833/80450135-266fab00-8921-11ea-84b1-bce6f54b62cf.jpg)

... fortunately it's not summer yet 😉

**Comment by dirkwhoffmann** [comment]
Great catch! It crashes the emulator here: 

<img width="867" alt="Bildschirmfoto 2020-04-28 um 09 08 05" src="https://user-images.githubusercontent.com/12561945/80458884-d0efca00-8931-11ea-9060-3631f5462556.png">

If I am not completely wrong, vAmiga tries to execute the fifth Blitter instruction in the following micro-program (marked with a red arrow). 

<img width="847" alt="Bildschirmfoto 2020-04-28 um 09 16 02" src="https://user-images.githubusercontent.com/12561945/80458915-dc42f580-8931-11ea-9b5b-3e5353576d0e.png">

Because there is no fifth instruction in this micro-program, the emulator crashes with a NULL pointer exception. However, the Blitter should't be at this spot at all, because the BLTDONE instruction in the line above should terminate the blit operation.

This is creepy 😬. I better hand it over to Scully and Mulder ... 👽

**Comment by dirkwhoffmann** [comment]
Just got back from Scully and Mulder: The culprit is Blitter operation 1518:

```
[2012] (299,165) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 15:0
[2012] (299,166) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 15:1
[2012] (299,167) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 15:2
[2012] (299,168) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 15:3
[2012] (299,169) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 15:4
[2012] (299,170) 023A8C  0 BCBS-A 4028 33C0 Blitter: pokeBLTCON0(DFC)
[2012] (299,170) 023A8C  0 BCBS-A 4028 33C0 Blitter: Instruction 13:5
```

Here is the thing: At cycle (299,169) in frame 2012 the Blitter is finishing up a type 15 operation. There is a single instruction to go, namely 15:5 (type 15 programs consist of 6 instructions). Before this instruction is executed, the game writes to BLTCON0 which changes the operation type to 13. This causes the Blitter to lookup the remaining instruction in the wrong table. It finds a NULL pointer there and says good bye 🥴.

**Comment by dirkwhoffmann** [comment]
Look at this! They have coordinated two consecutive Blitter operations so precisely because they use almost every cycle for it. The Blitter is literally glowing in the intro scene 🤯.

(DMA debugger view, brown = Blitter):

<img width="1003" alt="Bildschirmfoto 2020-04-28 um 13 21 50" src="https://user-images.githubusercontent.com/12561945/80481843-82ebbe00-8953-11ea-9adc-2cc3ac1d2a3c.png">

**Comment by Gianmarco72** [comment]
> Look at this! They have coordinated two consecutive Blitter operations so precisely because they use almost every cycle for it. The Blitter is literally glowing in the intro scene 🤯.

What could be the reason they decided to "squeeze" the Blitter so much for an intro scene? Big amount of data to move? (If I understand)

**Comment by dirkwhoffmann** [comment]
> What could be the reason they decided to "squeeze" the Blitter so much for an intro scene? Big amount of data to move? (If I understand)

That's hard to say. Either the animation takes a high amount of data to be shifted or they already prepare for the game in between. In either case, I haven't seen any program yet using the Blitter that much in a single scene. Amazing.

**Comment by mithrendal** [comment]
Maybe they are some blitter fanatics 🤓... I guess they are blitting two large memory blocks with at least 16 colors (hence in sum 4+4 bitplanes) into the screenbuffer and that makes the blitter glow. 

Maybe for the same effect they should have used dual playfield but when I remember correctly in dualplayfield you would only have 3 planes (hence 8 different colors each) for one playfield. So yeah to get these great colors scrolling vertically they had to make the blitter glow ....
