### ISSUE TITLE
Graphics problems with Out Run (U.S Gold).

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#331]
Here's how it should be (UAE)🤩:
![UAE](https://user-images.githubusercontent.com/45571833/81111175-f2961600-8f1c-11ea-816a-b14bedea62ab.jpg)
This is what happens on vAmiga 😣:
![vAmiga1](https://user-images.githubusercontent.com/45571833/81110448-d776d680-8f1b-11ea-9d6e-d3e57fe0de08.jpg)
![vAmiga2](https://user-images.githubusercontent.com/45571833/81110252-92eb3b00-8f1b-11ea-8c79-b84f89befbea.jpg)
Similarly as described on Issue #326, the game and audio are still running.

**Comment by dirkwhoffmann** [comment]
Quick findings: Outrun (1988)(U.S. Gold)[cr BS1][t +2 BS1].adf

<img width="1003" alt="Bildschirmfoto 2020-05-08 um 08 55 15" src="https://user-images.githubusercontent.com/12561945/81379679-d86d5b00-9109-11ea-97d4-6978ff789565.png">

At this point, the game executes a Copper list that is completely broken: 

<img width="401" alt="Bildschirmfoto 2020-05-08 um 08 56 08" src="https://user-images.githubusercontent.com/12561945/81379731-eae79480-9109-11ea-91fd-8569cf5bc75c.png">

**Comment by dirkwhoffmann** [comment]
Update: 
"Outrun (1988)(U.S. Gold)[cr QTX].adf" is the better test case, because it doesn't have the annoying cracker intro scene. 

SAE 0.9.11 (Turbo drive, Immediate Blitter): 👍

<img width="732" alt="Bildschirmfoto 2020-05-08 um 10 06 55" src="https://user-images.githubusercontent.com/12561945/81385717-212a1180-9114-11ea-80f9-071343999afa.png">

vAmiga: 🙈

<img width="1003" alt="Bildschirmfoto 2020-05-08 um 10 08 18" src="https://user-images.githubusercontent.com/12561945/81385754-30a95a80-9114-11ea-80e6-8944416b294b.png">

Bookmakers are open for business. I bet it's a Copper issue...

**Comment by dirkwhoffmann** [comment]
Got it. The addresses written to the Copper LC registers are outside the Chip RAM bounds and vAmiga had a bug w.r.t. Copper/Blitter Chip RAM mirroring. 

<img width="1003" alt="Bildschirmfoto 2020-05-08 um 13 08 57" src="https://user-images.githubusercontent.com/12561945/81400603-ce5d5380-912d-11ea-84db-29c64d6bc29f.png">
