### ISSUE TITLE
The Jetsons - Legend of Robotopia (MicroIllusions) doesn't boot.

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#348]
After the intro screen in pixel art appears, df0 stops the load (and drive's led blinks)😣:
<img width="868" alt="Schermata 2020-05-20 alle 17 39 16" src="https://user-images.githubusercontent.com/45571833/82467424-ef289000-9ac1-11ea-8979-59564b5302f8.png">
On UAE we can go to the future 🚀:
<img width="1072" alt="Schermata 2020-05-20 alle 17 37 30" src="https://user-images.githubusercontent.com/45571833/82467613-239c4c00-9ac2-11ea-94d5-963a1d5014e5.png">

**Comment by mithrendal** [comment]
This one looks funny. I bet playing it makes a lot of fun.

**Comment by Gianmarco72** [comment]
> This one looks funny. I bet playing it makes a lot of fun.

Absolutely 😃
When I was a kid I played a lot .. and always watched Jetsons on TV 😝

**Comment by dirkwhoffmann** [comment]
> On UAE we can go to the future 🚀:

UAE is awesome! We need to have this feature, too 🤤. I've never heard about the Jetsons though 🙄.

**Comment by dirkwhoffmann** [comment]
Confirmed. Same behavior as in SAE. Boots in UAE with weak settings (Turbo drive + Immediate Blitter).

**Comment by dirkwhoffmann** [comment]
There are multiple errors here. In v0.9.8, the first part of the loading sequence seems to work fine now. In contrast to v0.9.7, a movable mouse cursor appears:

<img width="995" alt="Bildschirmfoto 2020-06-06 um 08 21 50" src="https://user-images.githubusercontent.com/12561945/83937797-31dfad00-a7d0-11ea-8b91-9980f4600b06.png">

However, after a few seconds, the machine throws some CPU exceptions, resets, and enters Guru state👳🏽‍♀️.

**Comment by dirkwhoffmann** [comment]
The Jetsons in v0.9.8.1 😎:

<img width="1112" alt="Bildschirmfoto 2020-06-12 um 17 09 39" src="https://user-images.githubusercontent.com/12561945/84517473-a84c4580-accf-11ea-8519-8765547d9f9f.png">

**Comment by Gianmarco72** [comment]
Hmmmm... 🤔
Downloaded the v0.9.8.1:
<img width="396" alt="Schermata 2020-06-12 alle 18 56 40" src="https://user-images.githubusercontent.com/45571833/84527610-80b0a980-acde-11ea-87f2-e546604a4e4b.png">
... but:
<img width="912" alt="Schermata 2020-06-12 alle 18 51 50" src="https://user-images.githubusercontent.com/45571833/84526682-17309b00-acde-11ea-8617-8f3bae3f33c0.png">
<img width="912" alt="Schermata 2020-06-12 alle 18 49 51" src="https://user-images.githubusercontent.com/45571833/84526769-1ef03f80-acde-11ea-9216-5e407e136c9c.png">
Seems the same problem. My mistake? 😶

**Comment by dirkwhoffmann** [comment]
Hmm, OK, strange. I need to find out in which configuration I booted the game.

**Comment by dirkwhoffmann** [comment]
It works with 1MB Chip Ram (which was installed, because I tested the "5 to 12" demo). It runs in v0.9.8 with 1 MB Chip Ram, too. Do you remember your UAE setup?

**Comment by dirkwhoffmann** [comment]
Very strange. In UAE, it works with all memory configurations. In vAmiga, it breaks if Slow Ram or Fast Ram is enabled. It works well if Chip Ram is the only Ram. I have no idea how that can be.

**Comment by Gianmarco72** [comment]
Tried now on v0.9.8.1 with 1Mb Chip Ram and "Guru Meditation".
I use FS-UAE and my config is very simple (as you can see):
<img width="1343" alt="Schermata 2020-06-12 alle 19 59 18" src="https://user-images.githubusercontent.com/45571833/84532846-3ed83100-ace7-11ea-8031-0615e7c1585a.png">
(Kickstart 1.3)
Start the emulation and "boom"..:
<img width="1072" alt="Schermata 2020-06-12 alle 19 51 23" src="https://user-images.githubusercontent.com/45571833/84532466-91651d80-ace6-11ea-9bdf-40b6e96af001.png">
Then I tried also in SAE with first 512 Kb of Chip Ram, next with 1 Mb... and again, "Guru..." and "Guru..." 😵

**Comment by dirkwhoffmann** [comment]
It works here with the following config (v0.9.8.1):

<img width="635" alt="Bildschirmfoto 2020-06-12 um 20 02 12" src="https://user-images.githubusercontent.com/12561945/84533102-c2921d80-ace7-11ea-96b3-9354bc2d057a.png">

<img width="635" alt="Bildschirmfoto 2020-06-12 um 20 02 28" src="https://user-images.githubusercontent.com/12561945/84533123-cb82ef00-ace7-11ea-9dce-c23cb1b45fa8.png">

<img width="635" alt="Bildschirmfoto 2020-06-12 um 20 02 37" src="https://user-images.githubusercontent.com/12561945/84533128-cd4cb280-ace7-11ea-8556-eff3bba710a3.png">

**Comment by Gianmarco72** [comment]
Confirmed, works with Slow Ram disabled (v0.9.8.1):
<img width="912" alt="Schermata 2020-06-12 alle 20 14 55" src="https://user-images.githubusercontent.com/45571833/84534107-a1cac780-ace9-11ea-9c54-a442ad007bd0.png">
Tried in SAE with Slow Ram disabled: not work and a different crash happen (without Guru Meditation) during the title screen.

Now probably the question might be: why in UAE works with any mem config? 😓

**Comment by dirkwhoffmann** [comment]
Here is what I found out: The game scans the memory for certain word combinations. It starts by looking for $1000200.

<img width="980" alt="Bildschirmfoto 2020-08-20 um 17 04 04" src="https://user-images.githubusercontent.com/12561945/90790320-36642e00-e308-11ea-93a7-0b87cac1beef.png">

Without SlowRam, it finds it here:

<img width="980" alt="Bildschirmfoto 2020-08-20 um 17 03 34" src="https://user-images.githubusercontent.com/12561945/90790342-3b28e200-e308-11ea-8232-d6315bf4ed0f.png">

With SlowRam  enabled, it scans for a very long time, because it has to reach SlowRam first (located at $C00000). But even worse, it doesn’t find the same program fragment there and crashes shortly after.

On the real A500, there is no delay which is a strong indication that the program doesn’t reside in SlowRam (although the machine has 512KB of it). Therefore, I guess that the error happens much earlier. For some reason, Kickstart may assign the program SlowRam area in vAmiga, but ChipRam area on the real machine.

**Comment by dirkwhoffmann** [comment]
After the bank mapping mystery in the RTC area has been solved, it's time to return to this crime scene. As a start, I run FSUAE against vAmiga with the following settings (RTC has been patched to return 0 when a clock register is read): 

`./fs-uae --uae_chipset=ocs --kickstart-file=~/Desktop/Testing/kick13.rom  --uae_immediate_blits=true --floppy_drive_speed=0 --slow_memory=512 --floppy_drive_0=~/Desktop/Testing/Jetsons1.adf --floppy_drive_count=1 > ~/Desktop/fsuae.log`

The first difference occurs after reading cylinder 44: 

<img width="1162" alt="Bildschirmfoto 2020-08-28 um 16 16 13" src="https://user-images.githubusercontent.com/12561945/91578307-42746f00-e94a-11ea-8b7d-cc1d2e23c6cb.png">

Interestingly, blit 1221 is started with a different destination pointer (channel D). Shortly after, something fundamentally is going wrong. vAmiga reads in cylinder 47 whereas FSUAE reads in cylinder 48. 🙈

**Comment by tonioni** [comment]
There are 11 different Jetson variants (one original, different crack and trainer combinations). Which exactly is used for testing? Always include image checksum.

**Comment by dirkwhoffmann** [comment]
>  Always include image checksum.

Is there some kind of a checksum standard in the Amiga world? 

In case it's CRC-32, the checksum (of the boot disk) is as follows:

    > crc32 ~/Desktop/Testing/Jetsons1.adf 
    04f70604

**Comment by dirkwhoffmann** [comment]
@tonioni: By scanning the Jetsons' debug output for differences between UAE and vAmiga, I've noticed that UAE reads back CIAB::CRB as $84 and vAmiga reads it back as $80. This is because UAE initializes the registers as follows:

    ciaacra = ciaacrb = ciabcra = ciabcrb = 0x4; /* outmode = toggle; */

I don't think this is correct. Some time ago, I've written some tests displaying the initial values of the CIA registers (as far as these values can be grabbed by software because some registers are overwritten before my program starts). 

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Init/ciainit

Here is the result of test ciainit15 in UAE: The upper byte is CRB from CIA A (which gets overwritten during boot) and the lower byte is CRB from CIA B:

<img width="720" alt="Bildschirmfoto 2020-08-31 um 14 22 32" src="https://user-images.githubusercontent.com/12561945/91719908-6af0a900-eb96-11ea-9925-480d1039e110.png">

On the real machine (A500 8A) it looks like this: 

![ciainit15_A500_8A](https://user-images.githubusercontent.com/12561945/91719927-717f2080-eb96-11ea-9dc4-232080d71d9c.JPG)

Hence, I think bit 2 in CRB is 0 on startup (and the same holds for bit 2 in CRA).
 
I know it's a minor issue and it is unrelated to the Jetsons bug in vAmiga.

**Comment by dirkwhoffmann** [comment]
@tonioni: Small question: I'd like to print out a debug message in UAE when an interrupt hits in. Where is the best place in UAE to place my printf statement? 🙄

**Comment by tonioni** [comment]
>Some time ago, I've written some tests displaying the initial values of the CIA registers (as far as these values can be grabbed by software because some registers are overwritten before my program starts).

I read real initial values (by copying CIA contents at the very beginning of ACA500plus firmware which runs before KS code runs):
Timers are 0xFF. TOD counts are zeroed. Interrupt control is zero (but due to keyboard, CIA-A SP is set), control registers are zeroed.

> Small question: I'd like to print out a debug message in UAE when an interrupt hits in. Where is the best place in UAE to place my printf statement?

newcpu do_interrupt() probably works.

**Comment by dirkwhoffmann** [comment]
> newcpu do_interrupt() probably works.

That worked. Thanks!

Let’s recapitulate: Based on my review of the debug logs, I can pretty much rule out the Blitter and the Copper as well as Paula (no missing interrupts).  All OCS and CIA registers (pretty much) read back as expected. Bank mapping should be fine, too. 

If I was a medical doctor, I would diagnose this as being psychosamatic 🙄, but I won't give up. 

Maybe I should look at the CPU again. Because I run cputester with great success, a functional bug is unlikely. But what about interrupts? Because of the way IPL polling works, the CPU usually executes another instruction before an enabled interrupt is executed (e.g., Feud relies on this, #218). But if the IPL gets polled very late compared to a write into INTENA or INTREQ (some MOVE addressing modes behave this way if I remember correctly), the interrupt may happen immediately (before the next instruction is executed). Maybe I should check my CPU w.r.t. this behavior 🤔. I haven’t really tested this.

**Comment by tonioni** [comment]
IPL timing test is still not implemented. But generally you can expect next instruction always getting executed if previous wrote to INTENA or INTREQ. Of course there might be some special cases. I always do IPL poll during last memory access. Which isn't really correct but good enough until tester is done.

Also IPL is always polled at least 2 cycles before end of instruction (or earlier), it can never happen at the end of instruction due to way real 68000 microcode works.

Test cases: Warhead or IK+. If sound is wrong: interrupt is too early.

**Comment by tonioni** [comment]
Game seems to have part of copy protection code remaining (exception 3, illegal instructions etc). Perhaps it causes the problem (wrong exception 3 stack frame in some situations etc..)

Check if Vision Factory cracked version works, it seems to bypass copy protection completely. (CRC32=4Ab3FDC9, TOSEC "Jetsons, The - George Jetson and the Legend of Robotopia v1.0 (1989-11-06)(MicroIllusions)(Disk 1 of 2)[cr VF - Bencor Brothers]")

Your version is "Jetsons, The - George Jetson and the Legend of Robotopia v1.0 (1989-11-06)(MicroIllusions)(Disk 1 of 2)[cr PNA][a]"

**Comment by dirkwhoffmann** [comment]
> Check if Vision Factory cracked version works

No, it behaves the same way. Works fine with 512 Chip + 0 Slow, fails to boot with 512 Chip + 512 Slow.

**Comment by tonioni** [comment]
Quite strange. Game is (mostly) system friendly (exec is still scheduling tasks, game added vblank interrupt using system routines instead of replacing exception vectors, uses dos to load files etc) so there is no reason for it to try to do any memory detection or anything else too weird.

**Comment by dirkwhoffmann** [comment]
The cracked version works in SAE with lowest compatibility settings (Turbo drive, Immediate Blitter). SAE fails to load the copy protected version, because it doesn't handle the CPU trace flag stuff correctly. Hence, copy protection stuff can be ruled out from the possible error sources.

<img width="717" alt="Bildschirmfoto 2020-09-21 um 15 15 41" src="https://user-images.githubusercontent.com/12561945/93771586-03220100-fc1e-11ea-9f58-1ba16d7586de.png">

**Comment by dirkwhoffmann** [comment]
Update: The Blitter checksum discrepancies shown above are due to the timing of the DSKBLK interrupt. In Turbo drive mode, UAE and vAmiga both emulate a delay between a write to DSKLEN and the occurrence of the interrupt. vAmiga waits for 512 DMA cycles whereas UAE utilizes a raster line counter initialized by 2. After mimicking the UAE delays, all Blitter checksums match up to the point where vAmiga freezes. This means that the bug is likely to happen near the freezing point and not way before as my previous findings suggested.

<img width="1363" alt="Bildschirmfoto 2020-09-27 um 17 21 17" src="https://user-images.githubusercontent.com/12561945/94369008-94461b80-00e7-11eb-95ee-6111f9ae8e94.png">

I've also run the cracked version in the latest version of vAmiga using the Musashi core and experiences the exact same symptoms. This doesn't rule out the CPU as the culprit, but it strongly suggests to look at other components, first.

**Comment by dirkwhoffmann** [comment]
<img width="244" alt="Bildschirmfoto 2020-09-29 um 14 39 41" src="https://user-images.githubusercontent.com/12561945/94559862-240fd500-0262-11eb-8c5f-4977046e4e20.png">

Running "The Jetsons" with extended memory in vAmiga 😎:

<img width="899" alt="Bildschirmfoto 2020-09-29 um 14 30 35" src="https://user-images.githubusercontent.com/12561945/94559975-4e619280-0262-11eb-93d6-9d26e506efc4.png">

<img width="899" alt="Bildschirmfoto 2020-09-29 um 14 30 44" src="https://user-images.githubusercontent.com/12561945/94560045-5faa9f00-0262-11eb-892a-2bd3146b3f5d.png">

Solving issue #414 was the key to victory.
