### ISSUE TITLE
Question and Request :)

### ISSUE THREAD

**Issue by vigo** [dirkwhoffmann/vAmiga#363]
Well, as a macOS user, I'm super greatful and happy for this (and virtualC64) emulator. I couldn't find email address therefore I'm opening an issue which is not an issue :)

- Is it possible to create a separate / individual ADF editing tool? Few macOS versions ago, there were a great QLPlugs and ADF tools available. After Catalina almost evert 3rd party plugin stopped working.
- What about AGA chipset?  I hope will be available soon.

I wish I had enough swift coding skills to help this project out.

Again, a million thanks for these great projects...

**Comment by dirkwhoffmann** [comment]
AGA is very unlikely to come, but I might add full ECS support in future. Right now, only ECS Agnus is supported, but no ECS Denise. 

An ADF editing tool is really something I'd like to have myself. However, it's unlikely that I am going to write one myself in the near future. The reason is the same as for the AGA feature. I just don't have enough time for doing this.

To assemble ADFs, I usually use xdftool (command line). At first, I had some trouble to get it work on Catalina, because it needs an older Python version. I don't remember exactly what I did, but redirecting some symbolic links  did the trick (or was it just the PATH variable? I don't remember).

**Comment by vigo** [comment]
Thanks for the reply. amitools works fine with Python 3. I just made a quick fix on `relabel` feature. Well, I'm missing @cnvogelg's D64 qlplugins and tools. Unfortunately It doesn't work since 2/3 macOS releases...
