### ISSUE TITLE
Demo "911 Rescue (1997) (Limbo)" doesn't work

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#364]
Trying some demos (from Amiga's demoscene)..

When start the demo vAmiga stops in this screen:
<img width="912" alt="Schermata 2020-06-06 alle 19 40 33" src="https://user-images.githubusercontent.com/45571833/83950870-0ee3e600-a82e-11ea-8f2b-a7c58c61a0a6.png">
.. and Paula croaks 😣

Tested on SAE:
<img width="1436" alt="Schermata 2020-06-06 alle 19 38 47" src="https://user-images.githubusercontent.com/45571833/83950911-5d918000-a82e-11ea-9036-e90629a99017.png">
it works ... and Paula sings 🎶

**Comment by dirkwhoffmann** [comment]
Great catch! This might be a perfect test case for ruling out some of the remaining bugs (perfect in the sense that the bug shows up very quickly and SAE works well with weakest compatibility settings).

**Comment by Gianmarco72** [comment]
I think it's a good idea to try some demos too, which often take advantage of custom and M68000 chips (maybe).

**Comment by dirkwhoffmann** [comment]
This issue is getting interesting, because it's related to the TOD bug of the CIAs. If TOD bug emulation is disabled, the demo works: 

<img width="648" alt="Bildschirmfoto 2020-06-08 um 17 19 54" src="https://user-images.githubusercontent.com/12561945/84049220-76c03b00-a9ac-11ea-9e23-7360445d8c97.png">

<img width="995" alt="Bildschirmfoto 2020-06-08 um 17 18 09" src="https://user-images.githubusercontent.com/12561945/84049236-7889fe80-a9ac-11ea-9e85-49c045309bc8.png">

It becomes interesting, because the demo runs on a real A500 without any issues. The A500 has the TOD bug which means that TOD bug emulation is wrong.

**Comment by dirkwhoffmann** [comment]
> I think it's a good idea to try some demos too

Definitely. Demos usually push the machine to the limits. Maybe not this particular one. This is the biggest 🤢 I've ever seen 😂. But it serves the purpose. It exhibits a bug.

**Comment by Gianmarco72** [comment]
> It becomes interesting, because the demo runs on a real A500 without any issues. The A500 has the TOD bug which means that TOD bug emulation is wrong.

In other words, the "TOD bug" have a bug.😅

**Comment by Gianmarco72** [comment]
> This issue is getting interesting, because it's related to the TOD bug of the CIAs. If TOD bug emulation is disabled, the demo works:

Found another DEMO that works with TOD bug disabled:
"5 to 12 (1993) (Syndacate)"

**Comment by dirkwhoffmann** [comment]
I'm reopening this issue, because the applied fix breaks #388 and is likely wrong.

> It becomes interesting, because the demo runs on a real A500 without any issues. The A500 has the TOD bug which means that TOD bug emulation is wrong.

I've just run the demo on my A500 again, and it failed (it failed both when the disk was inserted on boot and it also failed when the disk got inserted after the hand & disk logo had shown up). Since this contradicts my own statement above, some more investigation ist needed. It might well be that I did run the demo on my A500+ and not on the A500 8A.

TODO: Unpack the A500+ and run the demo there.

**Comment by dirkwhoffmann** [comment]
Just double-checked that the demo really fails on the original A500 (it does). Hence, I think this issue can be considered resolved.
