### ISSUE TITLE
How to press the 'Del' and 'Help' keys?

### ISSUE THREAD

**Issue by KenDFish** [dirkwhoffmann/vAmiga#366]
I've been trying to revisit [Bloodwych,](http://www.bloodwych.co.uk/) a great "Dungeon Master" clone. On the original hardware, I'd play it by using a combination of keyboard and mouse, with the cursor/arrow keys used for the "WASD"-style movement, and the **Del** and **Help** keys used to rotate left and right. I believe other dungeon crawlers of the era (Eye of the Beholder, Knightmare) used a similar scheme.

What keys would these map to (I'm using a Macbook Pro), and is (or will there be) the ability to customise the mappings?

**Comment by dirkwhoffmann** [comment]
At present, the HELP key is mapped to F12. It's a little annoying when using a MacBook, because the fn key must also be pressed. The problem is that there are no free keys left on the Mac keyboard. I could add virtual keys on the Touch Bar, but of course that doesn't help on Macs without a Touch Bar.

**Comment by dirkwhoffmann** [comment]
I've just seen that the F12 <-> Help mapping is broken. At some point in the past, I did assign F12 to the menu item opening the machine configuration (because UAE uses F12). From that point on, F12 was no longer passed to the keyboard controller. In the next release, I'll map HELP to F11, but it's still not an optimal solution.

**Comment by dirkwhoffmann** [comment]
The next version will provide TouchBar buttons for Del and Help:

![IMG_0772](https://user-images.githubusercontent.com/12561945/96681579-c9a4f880-1377-11eb-8b68-de37712ac208.JPG)

This means:
- The Del key can be pressed via the corresponding TouchBar button or the virtual keyboard
- The Help key can be pressed via F11, the corresponding TouchBar button, or the virtual keyboard

Can I close the issue? I know it's not optional, because only a fraction of Macs are equipped with a TouchBar, but there's no free standard key to map the Del key to.

**Comment by KenDFish** [comment]
Well I've got a Macbook Pro, so it works for me :) Thank you!
