### ISSUE TITLE
Cannot use my USB mouse/trackball but only the trackpad

### ISSUE THREAD

**Issue by sy2002** [dirkwhoffmann/vAmiga#373]
I am using the vAmiga 0.9.8.4

When it comes to using the mouse (e.g. in Workbench or in games such as Oil Imperium) I am able to control the Amiga's mouse cursor using the trackpad of my MacBook Pro. But I am not able to use the mouse/trackball that I have connected to my MacBook via USB.

This is strange, as I can for example use all the menus of vAmiga using my USB trackball without any problem. But as soon as it comes to controlling anything "inside" the vAmiga (inside the emulation), only the trackpad works.

**Comment by dirkwhoffmann** [comment]
Did you select the external mouse as input device? Starting with v0.9.8.4, external mice are treated as separate devices:

<img width="276" alt="Bildschirmfoto 2020-07-03 um 08 01 05" src="https://user-images.githubusercontent.com/12561945/86436864-742ed800-bd03-11ea-8140-854b63fdd9a2.png">

**Comment by sy2002** [comment]
OHA! A typical PEBKAC...  :cold_sweat:
Thank you for your fast feedback!
(Closed)

**Comment by dirkwhoffmann** [comment]
I had to google "PEBKAC". Never heard it before 😂.

I am very interested if the external mouse worked for you. Thing is that the implementation is kind of a hack, because macOS is designed to support a single mouse, only (by using the standard APIs, all mouse-type devices are indistinguishable). The current implementation works well with my Logitech USB mouse, but it may fail for others.
