### ISSUE TITLE
Oil Imperium drills way too fast

### ISSUE THREAD

**Issue by sy2002** [dirkwhoffmann/vAmiga#374]
When trying to drill a well in Oil Imperium, the game is like 10x to fast.

(FS-UAE works fine)

Here is the game: [oilimp.zip](https://github.com/dirkwhoffmann/vAmiga/files/4866782/oilimp.zip)

**Comment by dirkwhoffmann** [comment]
I am having trouble to reproduce the bug, because the game doesn't let me drill 😫: 

<img width="1110" alt="Bildschirmfoto 2020-07-03 um 08 14 49" src="https://user-images.githubusercontent.com/12561945/86437691-4e0a3780-bd05-11ea-9bf9-1f0816fbb7ca.png">

I am the proud owner of an oil field in Iran and Ireland, and I also bought a tank. But neither the Irish nor the Iranians let me drill. Do I need a drilling license or maybe a visa? 😬 Hmmm, I shouldn't need a visa for Ireland, should I? But wait... the game is from the 80s... 🤔 Don't really remember how it was back then...

**Comment by mithrendal** [comment]
@sy2002 in which country is your oil field?

What about when we cheat and @sy2002 posts a saved snapshot from his oil field here? 😎🤞

**Comment by sy2002** [comment]
:-)

I think you have to little money left. Try this sequence:

1. Start a new game
2. Choose "Buy"
3. Choose "Oil field"
4. Choose "Middle East"
5. Choose e.g. "Jemen"
6. Answer "yes" when it asks you if you'd like to buy a concession
7. Choose e.g. "Jemen" again <== maybe you did not do this?
8. Answer "yes" when it asks you if you'd like to buy an oil field
9. Answer "yes" when it asks you if you'd like to drill
10. Choose "own" (!) when it asks you if you'd like to drill on your own (or use a specialist)
11. Experience way too fast drilling (it will be over in ~2 sec; you can compare to FS-UAE)

Side note for testing the "drilling":

I never had an Amiga when I was a kid (even though it was my dream computer. I "only" had a C64.). Therefore I need to admit that I do not know the Amiga well enough to really understand, how for example this Oil Imperium specific setup was solved on real hardware:

Oil imperium needs a mouse AND a joystick: Mouse for buying the well etc. and joystik for drilling.

As a layman I would assume: Put the mouse in port #1 and the joystick in port #2.

When I played the game yesterday on FS-UAE, FS-UAE did somehow auto-magically take care for me (**) and therefore I am not sure, how the game expects the configuration to be. Mouse in #1 / Joystick in #2 - or the other way round? or maybe even manually toggling?

re (**) What I mean by that: When drilling was to be done on FS-UAE, I used the cursor keys of my MacBook on FS-UAE and when done, I continued using my trackball. It somehow got it right auto-magically.

@mithrendal: I did not fully understand how vAmiga's Snapshot and "Save Machine" Feature works. Although I saved a snapshot file directly before drilling (attached to this comment as a ZIP), I am not able to load it properly: When I load it, I still need to insert the Kickstart again, insert all disks again and boot the virtual Amiga and when booting, the game starts from the beginning and not that the place when I did the snap shot. The Snapshots (and "Save Machine" on VirtualC64 are easier indeed: Save => Load => Play :-) )

Here is the Oil-Drill-Snapshot:

[Oil_Drill_Snapshot.vAmiga.zip](https://github.com/dirkwhoffmann/vAmiga/files/4870143/Oil_Drill_Snapshot.vAmiga.zip)

**Comment by mithrendal** [comment]
>When I played the game yesterday on FS-UAE, FS-UAE did somehow auto-magically take care for me

🙋🏿🙋🏿🙋🏼🙋🏻🙋🏻 me me me ... I know why ....  thats the automatique mouse/joystick switcher which active by default in FSUAE ...I am so proud of the concept ... because I proposed it once to Frode 😍 ... and he was so kind to implement that for us... that was already years ago ...

here is the parameter description from the FSUAE site...

```
joystick_port_0_autoswitch

Summary: "Automatic mouse/joystick mode for mouse port"
Default: 1
Example: 0
Since: 2.1.33
Type: boolean

When this option is enabled, and joystick mode is selected for port 0,
the port will automatically switch between mouse and joystick mode when
you perform joystick or mouse movement.

This is especially useful when you want to play a two-player game with
two joysticks, but need the mouse to get past cracktros or trainers. With
this option enabled, you can use both the mouse and the second joystick
seamlessly.

```

when it switches automatically it tells you with a nice text overlay which disappears some second later ...

**Comment by dirkwhoffmann** [comment]
I had no problems with the snapshot. I dragged it into the emulator window and I was ready to drill in no time 😎.

<img width="1110" alt="Bildschirmfoto 2020-07-03 um 17 09 20" src="https://user-images.githubusercontent.com/12561945/86482163-b41cac00-bd51-11ea-8183-ef03239e4e13.png">

 I also tried "Open..." from the file menu. As expected, another emulator instance was created and I was ready to drill:

<img width="1075" alt="Bildschirmfoto 2020-07-03 um 17 10 44" src="https://user-images.githubusercontent.com/12561945/86481677-bf230c80-bd50-11ea-81f3-dca52d98e628.png">

The games expects the mouse in port 1 (this is where the mouse is usually plugged in) and the joystick in port 2. 

The drilling speed issue is due to "auto warping". When the drill sequence has been loaded, the game does not turn off the drive motor and vAmiga runs at full speed. You can either turn it off in the preferences or you can click the small hourglass symbol in the status bar next to the frequency display. 

<img width="758" alt="Bildschirmfoto 2020-07-03 um 17 20 18" src="https://user-images.githubusercontent.com/12561945/86482135-a109dc00-bd51-11ea-9903-686a1169b200.png">

**Comment by sy2002** [comment]
@mithrendal Thank you! This is very impressive and a great feature that you invented! Superb usability.

@dirkwhoffmann Thank you for your detailed feedback! It works great for me: I switch the warp mode on for the normal game flow (because otherwise loading takes waaay too long - I am not used to that any more :-) ) and then, when the drilling comes up, I use the hourglass to slow down. After drilling, I switch warp back on again.

About the snapshots: It is great, that the snapshot I made worked for you :-)

For me it does not. I made a small screen capture film (which is unfortunatelly too large for being a GitHub attachment), so I used WeSendIt, which will delete it in 7 days from today on: https://wsi.li/dl/mhq4RWhbsqqGBtehT/

**Comment by dirkwhoffmann** [comment]
@sy2002 Thanks a lot for the screen recording. I think I know what the problem is. There is a bug that causes the emulator to refuse a snapshot if no Rom is specified in the default virtual machine settings. The emulator should not complain in this situation, because Rom data is part of the snapshot. I guess the emulator does the "readyToPowerUp()" check before the snapshot data is read in (which would install the Roms). 

#375 is a follow-up for the issue.
