### ISSUE TITLE
 Blast From The Past! gives black screen after executable has started

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#385]
This demo https://demozoo.org/productions/170897/

http://deadliners.net/blast.adf

Gives a black screen after the executable starts (same ADF works fine on my A500)

**Comment by dirkwhoffmann** [comment]
Another great catch!

<img width="734" alt="Bildschirmfoto 2020-07-21 um 19 36 23" src="https://user-images.githubusercontent.com/12561945/88087677-917bf700-cb89-11ea-89be-d9ecbaba5e4d.png">

Works in SAE with weakest compatibility settings (Immediate Blitter + Turbo Drive)

**Comment by dirkwhoffmann** [comment]
This one hangs in an "interrupt loop". The VSYNC interrupt is not acknowledged in the level 3 IRQ handler which causes the interrupt to trigger again and again. Clearly, the demo doesn't expect the VSYNC interrupt to happen here since it only clears the Copper IRQ bit in INTREQ. Unfortunately, this doesn't tell us anything about the real error source.

<img width="246" alt="Bildschirmfoto 2020-07-24 um 12 59 58" src="https://user-images.githubusercontent.com/12561945/88385410-91a90c00-cdae-11ea-913c-005d64942839.png">

<img width="980" alt="Bildschirmfoto 2020-07-24 um 13 03 04" src="https://user-images.githubusercontent.com/12561945/88385416-9372cf80-cdae-11ea-97b1-89a021448074.png">

Not sure if it is related to #383, but it might well be.

**Comment by dirkwhoffmann** [comment]
This one was related to #364 instead of #383 (which is still failing). It supports my hypothesis that the applied fix for #364 was wrong.  Reverting to the old TOD initialization code makes the demo work: 

<img width="927" alt="Bildschirmfoto 2020-07-26 um 07 21 24" src="https://user-images.githubusercontent.com/12561945/88472335-e2854580-cf11-11ea-980f-7b6b398c6eda.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.10
