### ISSUE TITLE
Add the ability to mount a .LHA file as a disk

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#387]
The ability to mount a .LHA file as a disk

**Comment by dirkwhoffmann** [comment]
To start working on this, I would need to have a specific test case in form of an existing LHA file, together with an instruction how the file can be booted in UAE on an OCS machine. I'm still unsure how to connect hard disks to the very old Amigas.

**Comment by emoon** [comment]
Somewhat related to this: Something that would be very useful for me when doing demo testing is the ability to launch a single executable in vAmiga. The way (I imagine) it could work is that vAmiga generates a dummy ADF file, "copies" the executable to the image and then have a `startup-sequence` file in `S:` that starts the executable.

**Comment by dirkwhoffmann** [comment]
> the ability to launch a single executable in vAmiga

I already thought about this, but it turned out to be not so easy. My idea was to add some adf tool which gets called in the background with some temporary files. But I got in trouble with Apples security mechanisms. If I call an application which is located in the resource bundle, macOS freezes my application for a couple of seconds (I guess it triggers some security checks). It doesn't happen for tools from /user/bin (such as zip or unzip). I call those to unpack adz files and there is no such delay.

**Comment by emoon** [comment]
I'm not sure how your ADF loader works but I assume you load them to memory right? So in this case the generation of the ADF image can all be in memory and never come back to disk.

**Comment by emoon** [comment]
This might be useful https://github.com/lclevy/ADFlib

**Comment by dirkwhoffmann** [comment]
#446 is a follow-up.
