### ISSUE TITLE
Drag and drop floppies should show targets on hover

### ISSUE THREAD

**Issue by bartgrantham** [dirkwhoffmann/vAmiga#402]
The current floppy drag-drop UI is nice, but it would be smoother if dragging and dropping floppies would immediately show the 4 floppies as drop targets (possibly with a cancel target, too), instead of dropping opening a dialog as it does now.

Unrelated: I have a number of UI enhancement requests that come to mind when using the app, are you ok with me posting them here?

**Comment by dirkwhoffmann** [comment]
> The current floppy drag-drop UI is nice, but it would be smoother if dragging and dropping floppies would immediately show the 4 floppies as drop targets

The problem here is that the drop zones would have to overlay the GPU canvas. It might be doable, but Xcode usually gets mad with overlapping UI elements. 

> Unrelated: I have a number of UI enhancement requests that come to mind when using the app, are you ok with me posting them here?

Yes, sure. Please post them here.

**Comment by DannyCork** [comment]
What would be even nicer would be if the drag and drop of floppies required no human intervention. I only every drag 1 floppy so the current dialog isn't required. 

I'm thinking a more user friendly logic would be :
if 1 floppy then boot floppy
if > 1 floppy present df0 df1 etc.. dialog.

**Comment by dirkwhoffmann** [comment]
> What would be even nicer would be if the drag and drop of floppies required no human intervention

For this purpose, vAmiga let's you choose a certain floppy drive as "drop target". 

<img width="718" alt="Bildschirmfoto 2020-12-08 um 06 34 45" src="https://user-images.githubusercontent.com/12561945/101446955-8bae6480-3924-11eb-9b8e-9837b801453a.png">

If a drop target is assigned, the floppy will be inserted automatically in this drive. 

In the meantime, I've also tried to find out if there is some kind of standard Cocoa way to implement overlays as Apple uses them in Quicktime. I am not 100% sure, but I think these GUI elements are not "official elements" and Apple did some hackery to implement them. Since I want to stick to standard Cocoa elements as much as I can, I close this issue for now. It would be a large amount of work to implement such overlays by hand and there are many higher-priority issues waiting to be worked on.
