### ISSUE TITLE
Support for OSes other than just macOS?

### ISSUE THREAD

**Issue by qeeg** [dirkwhoffmann/vAmiga#415]
I'd love to be able to work on this emulator, but I just CANNOT afford a Mac, nor justify the purchase of one even if I could. At the very least a Linux port of vAmiga would be highly appreciated.

**Comment by mithrendal** [comment]
Hi qeeg, 

from my view vAmiga has three building blocks, 
* the emulation of the 68000 CPU
* the emulation of the amiga hardware
* the user interface

when porting to linux the most work would be to reimplement the UI I think ...

where are your main fields of interest ? Emulation or UI ? Or is your interest primarily to bring vAmiga to your linux computer ?  

In a not to distant future we will port the emulation core of vAmiga to WASM/HTML5 then it will be runnable on other OSes like linux too ... we already did this for dirks [virtualC64](https://github.com/dirkwhoffmann/virtualc64web) this year ...

**Comment by emoon** [comment]
I'm going to port vAmiga to Linux at some point, but in my case I'm not interested in the UI as I only plan to use vAmiga as a debugger for Amiga demos, porting the core (CPU/Amiga hw) looks very straightforward so I'm not really worried about having issues with it really. 

That being said I have no ETA when I'm going to start with it because I have other things to do before.

**Comment by dirkwhoffmann** [comment]
> In a not to distant future we will port the emulation core of vAmiga to WASM/HTML5

Maybe vAmigaWeb could become what the iPhone DemoScene browser is for the C64 world.

**Comment by mithrendal** [comment]
yeah that would be cool  🤤 ... isn't that already the next point on our todo list for vc64web ? We have to complete first the action script buttons .... then we can start to investigate how that could look like in vc64web when interfacing csdb.dk like https://csdb.dk/release/?id=171112

...  and then do the vAmigaWeb demo party browser  ... @emoon I found the most promising db to browse would be this site http://www.pouet.net/prod.php?which=81094  ? What do you think ?

**Comment by dirkwhoffmann** [comment]
>  isn't that already the next point on our todo list for vc64web ? 

Yes, it is. Oh boy, there are so many cool things to do... 🥵

BTW, during the last weeks, I have spent more and time on YouTube. Yesterday I stumbled across these very cool Mandelbrot zoom videos. I did compute a lot of Mandelbrot images on my Amiga back in the day, but I lost them out of sight when I switched over to the PC (it wasn't so exciting on a monochrome Hercules card). When I saw this video on Youtube, I was blown away by the graphical improvement they have made: 

https://www.youtube.com/watch?v=8cgp2WNNKmQ

BTW, this is a very short video. Another one continues to zoom into the set for over 3 hours 😳.

Despite the huge step in visualization, they have also found new ways to compute the set more efficiently (e.g., by calculating a high-precision reference point and using this point to compute the neighborhood with low-precision deltas). This is all amazing stuff and now, I am thinking about implementing such a cool generator, too. 😍 

Here is the link to the 3 hour video: 

https://www.youtube.com/watch?v=a3XDry3EwiU

Disclaimer: Even if you only watch half of it in (which I did yesterday), the video continues immediately as soon as you close your eyes. In my case, it lasted the whole night 🙈.

**Comment by mithrendal** [comment]
> then I saw this video on Youtube, I was blown away by the graphical improvement they have made:

good idea I will go and explore now ... lets dig ⚒ into that mandelbrot mining land and find some gold mines ...

as a starting point I will use this explorer equipment ⛏🔍🔦 ....

https://github.com/cslarsen/mandelbrot-js

nothing to install easy to use ... just plain HTML5 Canvas and Javascript
 
wow ... look ... I found something ... at the depth of 7026 meter

![grafik](https://user-images.githubusercontent.com/17108995/94839530-6c242880-0417-11eb-8451-e4283ff0ce1b.png)


... maybe I am the only one who discovered this special place ? 😊  

lets dig deeper 

Oh my god ... 😱 this seems to be endless ... but wait ... something is strange 🤔... the deeper I go the slower my equipment digs ...  If I would be a CPU manufacturer I would totally hype this ...😂

ohh so beautiful ....

**Comment by mithrendal** [comment]
![6493CA51-08AE-4C4D-A2DB-0230DE700F0B](https://user-images.githubusercontent.com/17108995/94894502-c5c53b00-0489-11eb-88ef-b50213534673.png)


My favorite at 2:26:55

**Comment by emoon** [comment]
@mithrendal demozoo.org is likely the best db (will feature a API to be used in the future) also I think the topic of this issue is derailing a bit.

**Comment by qeeg** [comment]
Why was this closed? The issue of vAmiga not supporting other OSes hasn't been addressed at all.

**Comment by dirkwhoffmann** [comment]
> Why was this closed?

I closed it, because there are no immediate todo items and I thought it was clear was is going to happen. With some luck, there will be two spin-offs of the project in future. A Linux variant which aims at demo debugging and a web version based on web assembly. Both projects sound promising and I am looking forward to them. Personally, I don't have the resources to port the emulator to other OSes at the moment, because it's nothing that can be done in a week or so. Of course, there is always the possibility that somebody else picks up the project and ports the GUI to another OS (FSUAE emerged out of UAE that way). If this is going to happen, I would be more than happy about it.

**Comment by qeeg** [comment]
Except macOS is an OS that has such vendor lock-in, that I personally think it's straight up unethical to write an emulator that ONLY works on macOS.

**Comment by idrougge** [comment]
Then you shouldn't emulate an Amiga, which is just as known for its vendor lock-in.

**Comment by qeeg** [comment]
Except it's an important part of computer history, and should be preserved, but writing an emulator that only runs on macOS is NOT preserving it. I have the same issue with WinUAE as well.

**Comment by pedgarcia** [comment]
There are always other alternatives for most of the emulators so preservation is not an issue at all here. WinUAE is Windows-only as many other emulators we know and FS-UAE is the multiplatform alternative. vAmiga comes to add to the pile of alternatives, but in this case for macOS.

Not trying to polemicize here "Unethical" is a strong word considering vAmiga is free and open-source, which the author and the other contributors are donating their free time to make it happen.

Also, I disagree that macOS is an OS that has such vendor lock-in. Anyone can write and distribute macOS applications without having to go through Apple's store, for example. That is what happens with vAmiga and  Atari800MacX to mention a few. Also, although the UI is strongly attached to Apple's ecosystem, Swift is finding his way to other platforms so who knows if 1-2 years down the road, porting it would be straightforward.

**Comment by mithrendal** [comment]
@qeeg The word "unethical" is totally inappropriate in this context.🤔  I think your emotions were speaking.😭 You really really want that emulator, no ? 😉 If that was your motivation then I can really understand the cause of your feelings ... 

having said this ... I want to emphasise that the core (61% of the code) of vAmiga is indeed very portable ... it is only the UI part (30% of the code) which is platform dependend.

I would like to take this opportunity to thank @dirkwhoffmann for creating vAmiga with portability in mind ... 

* he especially took care of a very clean separation of the UI from the core so that other projects can very easily use the emulation core he has created ... 

* it is an awesome mind thrilling clean implementation. 

* he used the highly portable C++ and C language so that it can be ported

I will start soon and use his core (61%) and compile it to the web and connect an online scene db with lots of cool demos (like I did with his Virtual C64 and **the Commodore Scene database**, result is here https://dirkwhoffmann.github.io/virtualc64web/ ) ... that will be a lot of fun for me ... thanks again dirk 😍 for creating this amazing mindblowing code
