### ISSUE TITLE
Prince of Persia loads all the way ,but doesn't open

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#426]
Prince of Persia loads all the way ,but doesn't open. I have tried loading with normal loading and async fifo. Also tried with Agnus 8362 and 8375. Works in FS-UAE 3.0.5

 Link to image:
http://archive.org/download/Commodore_Amiga_TOSEC_2012_04_10/Commodore_Amiga_TOSEC_2012_04_10.zip/Commodore%20Amiga%20%5BTOSEC%20v2012-04-10%5D%2FGames%2F%5BADF%5D%2FCommodore%20Amiga%20-%20Games%20-%20%5BADF%5D%20%28TOSEC%202012-02-27%29%2FPrince%20of%20Persia%20v1.0%20%281991%29%28Domark%29%28GB%29%5Bcr%20Angels%5D%5Bf%20AGA%20SR%5D%5Bt%20%202%20Angels%5D.zip

Regards,
Ben.

**Comment by dirkwhoffmann** [comment]
Great catch! Quick findings:

- Works well with a Turbo drive.
- Freezes here if an original drive is selected:
<img width="980" alt="Bildschirmfoto 2020-10-22 um 07 20 05" src="https://user-images.githubusercontent.com/12561945/96828713-6b8c1a00-1438-11eb-820c-84ac6b5fd1fc.png">

In this code, the game waits for the DSKBLK bit to be set in INTREQ.

Interestingly, the game modifies the DSKSYNC word, but I don't know if this is related to the bug:

<img width="980" alt="Bildschirmfoto 2020-10-22 um 07 25 11" src="https://user-images.githubusercontent.com/12561945/96828849-a8f0a780-1438-11eb-899f-3374ac94bde5.png">

BTW, the synchronous FIFO will go be gone in the next release. The FIFO will always be emulated asynchronously (except for Turbo drives, because there is no such thing as a FIFO in that case).

**Comment by bnice** [comment]
Hi,

Interesting how the turbo mode works better in some situations, I have to add testing with turbo drive on to my test scenarios. I did spot in the Git Hub contents sync FIFO was going in the comments :-)

**Comment by dirkwhoffmann** [comment]
Found it, it's not a bug. The game uses a simple DSKSYNC copy protection (don't how this kind of protection is called officially). It is very simple: The original disk has a non-standard SYNC mark on it (in this case $4891) which is not duplicated by many copy programs. The program enables DMA in sync mode which means that the disk controller starts DMA only when it has found a SYNC mark. Here, the game expects the special SYNC mark on track 42 and freezes because the mark is never found:

<img width="996" alt="Bildschirmfoto 2020-10-22 um 16 55 30" src="https://user-images.githubusercontent.com/12561945/96890644-1e379900-1488-11eb-901c-ae136f4aa528.png">

Fortunately, vAmiga is already equipped to break this 😎. Simply enable this option:

<img width="996" alt="Bildschirmfoto 2020-10-22 um 16 55 41" src="https://user-images.githubusercontent.com/12561945/96890748-3dcec180-1488-11eb-80c5-07dd4ad0ac38.png">

You can enable it while the emulator is running. The game will immediately continue to load and start as expected. 

You can also make the game work by enabling the first piracy option which tells vAmiga to write-protect the DSKSYNC register. If this option is used, it has to be enabled before the game modifies the DSKSYNC register of course.

What I don't understand is the fact that it works in UAE out of the box. Standard ADFs don't store SYNC marks which means that the emulator cannot restore the faulty SYNC mark by itself 🤔.

**Comment by bnice** [comment]
Wow, I use to think I new a fair bit about the Amiga, but your knowledge is next level. It's few too many settings to remember just to get the one game going. I will press on with testing. So, far we have only had disk handling issues, which is great. I do play one game of each image,  but I don't get far, so it far from an extensive test 🙂.

**Comment by dirkwhoffmann** [comment]
> I do play one game of each image, but I don't get far, so it far from an extensive test

I really appreciate your testing efforts, especially because I am kind of stuck at the moment. With #384 and #377 there are at least two big bugs remaining, but I just don't get a grip on them. Now, I am hoping that some other bug will be found that has the same root cause, but is easier to identify. 

Please don't worry about false-positives. If you report a bug that turns out to be none, that's just part of the game of software testing. 

> It's few too many settings to remember just to get the one game going

That's one reason why I removed the synchronous FIFO option. At the time where the emulator was very unstable, I used this option for debugging. Since then, the emulator has become much more reliable, so there is no real need for this option any more. In general, I think, less options are better, because any new option comes with the risk of confusing users.

**Comment by bnice** [comment]
Hi, rechecked on FS-UAE and it works?
