### ISSUE TITLE
Broken title screen on Double Dragon 2

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#433]
The title screen seems not to be perfect 😓
<img width="912" alt="Schermata 2020-11-03 alle 23 16 14" src="https://user-images.githubusercontent.com/45571833/98047188-cf94e200-1e2b-11eb-9660-e10fa11a1f23.png">

Double Dragon II (1990)(Virgin Mastertronic).zip

**Comment by dirkwhoffmann** [comment]
This one turned out to be easy (it's an OCS/ECS issue). The game requires OCS Agnus to work:

<img width="1019" alt="Bildschirmfoto 2020-11-07 um 08 02 57" src="https://user-images.githubusercontent.com/12561945/98434515-b2cd0880-20d0-11eb-90b6-d0198833e4a2.png">

Same in UAE. 

OCS Agnus: 

<img width="717" alt="Bildschirmfoto 2020-11-07 um 08 08 50" src="https://user-images.githubusercontent.com/12561945/98434525-bfe9f780-20d0-11eb-97e4-be6714c05d01.png">

ECS Agnus: 

<img width="717" alt="Bildschirmfoto 2020-11-07 um 08 05 42" src="https://user-images.githubusercontent.com/12561945/98434526-c4aeab80-20d0-11eb-8c72-7a8d483f3152.png">

**Comment by Gianmarco72** [comment]
Oh I see .. so the differences between the two generations of chipset generate some incompatibilities with some software 👍🏻
When I was young I remember I had this game on my Amiga and it worked well. Now I know that I have the first generation of A500 (yes, I have it yet) 😁

**Comment by dirkwhoffmann** [comment]
> Now I know that I have the first generation of A500

I remember that my original Amiga 500 had Kick 1.2 on it. I think these machines are pretty rare these days (all Amigas which I got from eBay had Kick 1.3 installed). Unfortunately, my original machine doesn't exist any more 😢.

**Comment by Gianmarco72** [comment]
My Amiga has Kickstart 1.2 😁 I bought it in May 1988 ... ops, my parents bought it,  I was 15 years old and somewhere I still have the receipt of purchase.😜
