### ISSUE TITLE
Ignore dsync write and always find sync, why needed?

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#439]
Hi,

I am just curious why we need the options Ignore dsync write and always find sync?

These options don't exist in FS-UAE and it seems to handle the cases where "always find sync" is needed "Prince of Persia" and "Pro Tennis Tour 2" in my collection.

 I think it is because there some feature of  adf format not supported in vAmiga?

**Comment by dirkwhoffmann** [comment]
> I think it is because there some feature of adf format not supported in vAmiga?

I don't know the reason why it works in (FS-)UAE out of the box. The reason is buried deeply inside the code. What I know for sure is that there is no additional information inside the ADF. ADFs are a byte-level dump of sector data and do not store a single bit of additional meta-information.

**Comment by dirkwhoffmann** [comment]
I think I figured it out.

A brief recall: 

- The standard sync word is 0x4489.
- Prince of Persia changes the sync word to 0x4891 and moves to cylinder 42.
- Because vAmiga doesn't find 0x4891 there (it still finds 0x4489), it loads forever.

Here is the thing: When the standard sync sequence is read on cylinder 42, the FIFO buffer contains AAAAAAAA4489.

In binary, this is: 
      ...1010 0100 0100 1000 1001

Now, let's look at the FIFO buffer three bits earlier (the FIFO is filled bit by bit):
      ...1010 0100 0100 1000 1

   Translating this back into a hexadecimal number results in: 
     ...1010 0100 0100 1000 1 = ...1 0100 1000 1001 0001 = ...0x4891

This is the sync sequence used by the prince.

One big question remains: Why on earth is the prince doing this? 😬

**Comment by dirkwhoffmann** [comment]
Other games were affected, too. Now, Emerald Mine also loads without resorting to any "Piracy" option:

<img width="988" alt="Bildschirmfoto 2021-01-17 um 17 06 29" src="https://user-images.githubusercontent.com/12561945/104849042-fd94a900-58e7-11eb-8a7d-8eb5ef03e467.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.17.
