### ISSUE TITLE
Black Lamp graphics errors

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#44]
The mouse doesn't succeed in controlling the movements of the main character.

[Comp.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3267659/Comp.adf.zip)

**Comment by dirkwhoffmann** [comment]
Uhhhh, what a strange game 😳.

Controlling the character seems to work (in my opinion). I think the main issues are the various graphics errors (most likely due to incompatible Copper / Blitter timing). 

Interestingly, no sprites are involved (no DMA except audio): 

<img width="822" alt="Screenshot 2019-06-12 at 13 54 45" src="https://user-images.githubusercontent.com/12561945/59355185-deef2900-8d26-11e9-87d4-7bf83217a8b8.png">

**Comment by Alessandro1970** [comment]
With last 0.29 release the intro menu in not more visible:
<img width="887" alt="Schermata 2019-07-18 alle 00 11 27" src="https://user-images.githubusercontent.com/34916641/61415368-b8597a80-a8f0-11e9-8f7c-fcda76756d1d.png">

**Comment by dirkwhoffmann** [comment]
Seems to be fine now: 

<img width="893" alt="Bildschirmfoto 2019-07-22 um 16 02 56" src="https://user-images.githubusercontent.com/12561945/61638715-425f6580-ac9a-11e9-8b63-8f1e8b09e61d.png">

**Comment by Alessandro1970** [comment]
Black Lamp does not work anymore, graphics bugs again.

**Comment by dirkwhoffmann** [comment]
> Black Lamp does not work anymore

😫

**Comment by dirkwhoffmann** [comment]
When taking a still image, it looks like in the old version:

<img width="858" alt="Bildschirmfoto 2019-08-11 um 18 11 22" src="https://user-images.githubusercontent.com/12561945/62836611-3d704f00-bc65-11e9-8eb9-93598ef1073f.png">

However, the characters don't move as smoothly as they do in SAE (I guess these are the graphics errors you are talking about). Do you remember if it was ever better? In my post above (where I said it seems to be fine now), I might have just looked at a still image. I don't remember exactly on what my judgement was based on.

**Comment by Alessandro1970** [comment]
Yes, before it run smoothly.
Now there are some errors while the characters are walking, and some errors into the borders sometimes.
If a shapshot is done no errors are visible....

**Comment by dirkwhoffmann** [comment]
I just checked versions 0.23, 0.29, and 0.29.1. In 0.23, the game crashes. In 0.29 and 0.29.1, the characters seem to have the same flickering issues that we see in the lastest release. I think it's due to some subtle Copper bug that stops the Copper when it shouldn't (it can be a simple timing issue that makes a certain WAIT statement fail all the time). When R-type II loads, a similar flickering occurs in the 3D scene where the spaceship can be seen from behind.

**Comment by Alessandro1970** [comment]
V3 same flickering issues

**Comment by dirkwhoffmann** [comment]
The game is still 🤢, bus guess what: No more flickering 😎.
