### ISSUE TITLE
Update feature like for VirtualC64

### ISSUE THREAD

**Issue by guyfromouttaspace** [dirkwhoffmann/vAmiga#454]
Just an idea: Since the update feature works so easy for VirtualC64, do you consider to provide some similar working update mechanism (working straight out of the application by just clicking "search for update")?

**Comment by dirkwhoffmann** [comment]
After wasting another hour with Sparkle today, I've decided to say good bye to the framework. It's not like the framework is bad, it's just that a lot of stuff can go wrong and it's often not quite clear what the root cause is. 

Until there are better options, I'll distribute vAmiga via the GitHub releases page. The same holds for VirtualC64. New releases won't utilise Sparkle any more.
