### ISSUE TITLE
Writing a second, cross-platform GUI for vAmiga?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#520]
During the last couple of days, I was thinking about the pros and cons of writing a second GUI for vAmiga. The major goal would be to make vAmiga accessible on Windows and Linux. 

A couple of month ago, I experimented with SDL and SFML which resulted in a proof-of-concept emulator called vAmigaBM (vAmiga Bare Metal). However, I feel that this is a dead-end. The major selling point of vAmiga is it’s sophisticated GUI (I think) and this selling point is just no longer there in vAmigaBM.

I browsed the web for a quick overview of cross-platform GUI frameworks. QT and GTK seem to be the two big players, but I also noticed that wxWidgets got some positive reviews.

My current understanding is:

- QT is massive. Furthermore, it only mimics the native look and feel by using skins.
- GTK is Linux centric and will definitely look like an app from outer space when run on Windows.
- wxWidgets is lightweight and maps to the real GUI elements of the OS.

From this quick analysis, wxWidgets seems like a suitable candidate, since I personally dislike apps that don’t exhibit a native look and feel. However, there are other requirements: The frameworks needs to be fast (at least for keyboard and mouse events), and it needs to be capable of handling complex UI interfaces such as the Inspector window with all of it’s sub panels.

Every feedback is welcome, especially if you are aware of any reasons why choosing wxWidgets would be the wrong decision.

**Comment by dirkwhoffmann** [comment]
> I hope this remains a "second" GUI, and does not become the primary

Yes, if I ever write it, it will be a second GUI, at least as long as I stay on the Mac platform. If Apple does continue on the path it has taken (e.g., locking down macOS more and more,  implementing their plans to actively scan our devices, etc.) I will say good bye at some point. 

I just run the SwiftUI version. Interestingly, it doesn't look like a real native macOS app. For some reason, many controls look different. SwiftUI is another Apple move I didn't really get. But maybe the technology is just still premature yet.

**Comment by shinra-electric** [comment]
> Yes, if I ever write it, it will be a second GUI, at least as long as I stay on the Mac platform. If Apple does continue on the path it has taken (e.g., locking down macOS more and more, implementing their plans to actively scan our devices, etc.) I will say good bye at some point.

Well, I'd agree in principle, though I don't think that's what they are really doing. Federighi has said many times it's going to remain open. Also, terrible reporting has mis-represented what that CSAM thing actually does. And it looks like they are backing down a bit now, but in any case this is off topic...
 
> I just run the SwiftUI version. Interestingly, it doesn't look like a real native macOS app. For some reason, many controls look different. SwiftUI is another Apple move I didn't really get. But maybe the technology is just still premature yet.

Some of the controls do look a bit different, but this may be down to me messing around, trying different things. I couldn't adjust  the size of the slider control, but I believe it's possible now. And I tried to use SF Symbols or (emoji) rather than images. 

They are definitely focusing on iOS over macOS right now. There are still lots of things that are unimplemented or are just terrible to use right now. But it's going to improve, and has already improved a huge amount since the first release. 

SwiftUI in general is great though. Not only is it easy to use, but it's cross-platform (with a little bit of work). 

But again, this is off-topic. We should be talking about the cross-platform stuff....
