### ISSUE TITLE
Angels Cracktro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#521]
Freezes right after starting.
Sorry in case it is just a problem with the WebAssembly version, lol

[Angels.crack06.zip](https://github.com/dirkwhoffmann/vAmiga/files/7141006/Angels.crack06.zip)

**Comment by dirkwhoffmann** [comment]
In v1.1b1, it freezes here (I guess it's the same in the Webassembly version):

<img width="853" alt="Bildschirmfoto 2021-09-10 um 05 18 05" src="https://user-images.githubusercontent.com/12561945/132798366-4638848a-4ba7-45b8-81d5-c54ca200fb8e.png">

This is what the CPU is doing at this point:

<img width="980" alt="Bildschirmfoto 2021-09-10 um 05 19 52" src="https://user-images.githubusercontent.com/12561945/132798400-f4f82e31-9471-4ff7-9844-119c250083a7.png">

Interestingly, the demo seems to be stuck in a loop that reads BLTDDAT. This register is rarely read, because it is unusable by the CPU. Needs further investigation...

**Comment by dirkwhoffmann** [comment]
This one was easy. I simply need to treat the BLTDDAT register the same way as I treat all write-only registers (BLTDDAT is special, because the register is completely unusable by the CPU).

In fact, to remove the bug, I had to remove old code rather than adding new. Now, it works as expected:

<img width="853" alt="Bildschirmfoto 2021-09-10 um 08 41 05" src="https://user-images.githubusercontent.com/12561945/132895151-7d4f2aca-f140-49e9-aad5-a4103ebbf74c.png">

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
