### ISSUE TITLE
Navy Seals Trainer

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#543]
Guru Meditation instead of displaying the trainer menu.
[Navy Seals (1991)(Ocean)[cr QTX].zip](https://github.com/dirkwhoffmann/vAmiga/files/7190369/Navy.Seals.1991.Ocean.cr.QTX.zip)

**Comment by dirkwhoffmann** [comment]
Findings: In vAmiga, it works with ECS Agnus and fails with OCS Agnus.

The culprit is here:

    // Returns the line in which the VERTB interrupt is triggered
    isize vStrobeLine() { return isECS() || MIMIC_UAE ? 0 : 1; }

If changed to this, it works:

    // Returns the line in which the VERTB interrupt is triggered
    isize vStrobeLine() { return 0; }

The original implementation is based on what we’ve seen on @mithrendal’s A1000. See 

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Interrupts/vblank

for details.

@mithrendal: Could you perhaps try to run the Navy Seals demo on the A1000? If it produces the Guru, vAmiga is right. If it runs the game, vAmiga's interrupt timing is wrong.

**Comment by dirkwhoffmann** [comment]
More findings: It works if OCS Agnus is selected in combination with Kickstart 1.2. It only fails with OCS + Kick 1.3.

Maybe, @mithrendal could boot his A1000 with Kick 1.3 and try to reproduce the Guru.

**Comment by dirkwhoffmann** [comment]
Update: Real A1000 with Kickstart 1.2:

![65377625338__9BE761C4-002A-48C2-966B-25B375C2D42B](https://user-images.githubusercontent.com/12561945/133943009-d10b257e-835d-4847-9fc4-ff4dcf2061ad.jpeg)

In vAmiga, it works with Kick 1.2, but it maybe another revision. 

We didn't manage to run Kick 1.3 on the A1000, yet.

**Comment by chris70c** [comment]
It is quite unlikely that it requires KS1.2, the game Navy Seals is from 1991 and KS2 was already out.
In WinUAE works with any configuration from A500 512K KS 1.2 to A1200 KS3 and everything in between.

**Comment by tonioni** [comment]
VB interrupt delayed by 1 line (mis-)feature is only in A1000 Agnus. Internally VB start line is line 0 if A1000 Agnus, last line of field if later Agnus. VB Strobe gets sent to Paula during next line.

**Comment by mithrendal** [comment]
@tonioni does WinUAE emulate this (mis-) feature when A1000 Setting is selected ?

**Comment by dirkwhoffmann** [comment]
OK, I see, there seem to be four OCS revisions (2 if we restrict ourselves to PAL):

- 8361 (DIP) - Amiga 1000 (NTSC); Amiga 2000 model A (NTSC)
- 8367 (DIP) - Amiga 1000 (PAL); Amiga 2000 model A (PAL)
- 8370 (PLCC) - Amiga 500 to Rev 5.x (NTSC); Amiga 2000 model B to Rev 4.5 (NTSC)
- 8371 (PLCC) - Amiga 500 to Rev 5.x (PAL); Amiga 2000 model B to Rev 4.5 (PAL)

What I understand from the posts above is that UAE emulates a 8371 by default (if OCS Agnus is selected) which doesn't have the bug. Mithrendal's A1000 has a 8367 because all A1000's are equipped with this chip.

This means that I should add another OCS revision to the list of supported Agnus chips in vAmiga (the user will be able to choose either 8367 or 8371, besides the ECS variants).

**Comment by mithrendal** [comment]
we tested with these three guys 

![image](https://user-images.githubusercontent.com/17108995/133984689-13ead187-a608-4c3a-8edf-1334346dd45a.png)

**Comment by tonioni** [comment]
WinUAE A1000 Agnus option is "hidden" in advanced chipset options (it is also automatically enabled if A1000 Quickstart). 
btw, A1000 Agnus bug also affects sprites (VB period == sprite logic inhibited).

There are basically 4 different (at least some parts of internal logic has differences) Agnus versions:
- A1000
- OCS
- ECS
- AGA (not  really Agnus but differences aren't that big compared to ECS)

PAL/NTSC differences are same in all variants.

**Comment by dirkwhoffmann** [comment]
In the next release, there will be four Agnus revisions to choose from:

```
enum_long(AGNUS_REVISION)
{
    AGNUS_OCS_DIP,          // Revision 8367 (A1000, A2000A)
    AGNUS_OCS_PLCC,         // Revision 8371 (A500, A2000B)
    AGNUS_ECS_1MB,          // Revision 8372 (A500, A2000B)
    AGNUS_ECS_2MB           // Revision 8375 (A500+, A600)
};
```

Navy Seals Trainer works with all of them except AGNUS_OCS_DIP (which matches what we've seen on the real A1000).

**Comment by dirkwhoffmann** [comment]
I think this one can be closed. Thanks to all who have helped to clarify the differences between the various Agnus revisions out there.
