### ISSUE TITLE
Desert Dream by Kefrens - Tunnel sequence bug

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#571]
Reported by @mras0: https://github.com/vAmigaWeb/vAmigaWeb/issues/3

A500 8A: 🥰
https://user-images.githubusercontent.com/12561945/138496596-180bdf42-e255-4c62-aabe-d0c23c089663.mov

vAmiga: 🙈

https://www.youtube.com/watch?v=ZiclbqL5pFA

The dashed lines appear solid in vAmiga. I bet it's a Line Blitter issue...

**Comment by mras0** [comment]
Not to bother you, but have you reported these to Toni? I can see you've been busy adding more testcases, and since they're probably not super urgent, I can understand waiting till you're done. Mostly just making sure you're not waiting for me to report them, and since I think he's planning for a major release in the near future, he may at least would like to know about them. Keep up the good work 👍

**Comment by dirkwhoffmann** [comment]
> Not to bother you, but have you reported these to Toni?

Not yet. My plan is to sum up all findings when I'm done with the Line Blitter. Unfortunately, this all has to wait for a couple of days because I am buried under a pile of work at the moment.

**Comment by dirkwhoffmann** [comment]
I think this one can be closed.

@tonioni: I've filed a separate bug report in the UAE repo for each issue we've found and discussed in this thread.

@mras0: Please let me know if I've forgotten something (UAE related items were the persistence of ASH, BSH, and SIGN as well as the handling of the Blitter zero bit).

**Comment by mras0** [comment]
Looks good to me! Didn't mean to rush you, other things can take priority even over amiga stuff :)

**Comment by dirkwhoffmann** [comment]
> other things can take priority even over amiga stuff :)

Yes, indeed. Sometimes there is important C64 stuff to do that just can't wait 😎.

**Comment by dirkwhoffmann** [comment]
The new and improved Line Blitter is part of v1.1b6 which is now online.
