### ISSUE TITLE
Disk "System Request" Error

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#593]
This disk works in FS-UAE, but here it gives an error on load when the file does exist.
![Screen Shot 2021-11-02 at 2 29 58 PM](https://user-images.githubusercontent.com/31462938/139924346-cf4582f4-f08d-40e9-9a48-fae2d615765d.png)

[Perfect Sound v3.0 (1989)(Sunrize)[cr Sector 96].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/7463208/Perfect.Sound.v3.0.1989.Sunrize.cr.Sector.96.adf.zip)

**Comment by mras0** [comment]
Just curious what, but what configuration are you running and what steps are you taking to trigger that error? (I tried it in  chris70c's online version of vAmiga and the program loaded fine in a classic config KS1.3/512K chip/512K fast).

However it seems that loading the sample "Sounds/you_become_naked" presents a "read/write" error requester (reproducible in multiple emulators with different configurations), so it seems likely that the program is buggy. Other samples seems to work fine.

**Comment by mras0** [comment]
@bluecursor: I didn't mean to necessarily imply that this isn't a real issue, just because the original program is buggy (most emulator bugs are caused by buggy software that works fine on the real hardware (at least in certain conflagrations)), so please reopen (unless @dirkwhoffmann says otherwise) if it's something that you can reproduce that behaves differently in other emulators or even better on the real hardware :)
