### ISSUE TITLE
The Disk class should store the native file system path internally

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#600]
Right now, the Disk class does not store any path or filename information internally. @chris70c requested this extension, because the filename is used in his web emulator at various places.

**Comment by chris70c** [comment]
Is not a big deal, I think it might be better if these details are handled from the emulator interface; I can easily save the filename of each drive in the db together with the snapshot binary. Unless you think it might be of use to you on the mac side I don't think it is worth to implement it directly in the snapshots.

**Comment by dirkwhoffmann** [comment]
> Unless you think it might be of use to you on the mac side I don't think it is worth to implement it directly in the snapshots.

OK. Right now, I don't have any use for it on the Mac side, so I keep the snapshot format as it is.

**Comment by chris70c** [comment]
BTW, saw you changed the snapshot version to 1.0.6 in latest vAmiga, old 1.0.4 are no longer working, what has changed?

**Comment by mithrendal** [comment]
vAmiga serializes all of its datastructures into the snapshots for all components ... that is paula, the cpu and so on... when something has been modified in the structure lets say for example a new flag in the blitter emulation code then this means that you cannot reliable load older snapshots because the serialized datastructures are shifted and for example do not have the same length ... this happens  ... I solved this by checking the snapshot version from the snapshot header and show them to the user as invalid ... and that it has to be removed

for example here we have vc64web v4.5 and I have stored a snapshot from 
Abbaye des morts with v4.3 .... below is a snapshot of Archon taken with version 4.4 which is still compatible with v4.5 

![image](https://user-images.githubusercontent.com/17108995/141015289-23ae699d-a382-4400-9f3a-04cbcb1617bf.png)

**Comment by chris70c** [comment]
Yes I understand the process, it is a but unfortunate because when you have a collection of snapshots they become unusable every new version which can be quite annoying, lol
WinUAE save states can survive several versions, still using save states from 2.x in latest 4.x; maybe it could be possible to consider a different way, for example if the snapshot did not include a specific feature that feature can be set to the default value this way you could still use your snapshots.
Of course I understand that in some cases it might not be possible when updating from 1.1 to 2.0 for example because there might be too many changes but it could be enough maybe to have them survive the update from 1.1 to 1.2 let's say.

**Comment by dirkwhoffmann** [comment]
Based on my experience with VirtualC64, I expect the Snapshot format to remain a moving target in both emulators. Originally, I thought the format would stabilise at some point, but it did not. There is always a new variable coming in or another variable vanishing. In VirtualC64, I used the following rule of thumb: The snapshot format remains the same if the version number jumps from x.y.z to x.y.(z+1), but it is usually different between x.y and x.(y+1).

I don't want to go down the UAE road in this case, because it would clutter the code with lots of version number checks and the result would be a nightmare to test. A lot of bug reports would come in saying that some old snapshot is no longer working. We simply don't have the man power to debug such stuff.
