### ISSUE TITLE
Trackmo for Testing?

### ISSUE THREAD

**Issue by tcurdt** [dirkwhoffmann/vAmiga#641]
Cool project. I love it. Especially the details of the disk sounds :)

Our trackmo seem to do some nasty things that I wasn't aware of back in the days.
Seems like it can be used as a benchmark for simulators now :)

I cannot remember which emulator worked - but vAmiga is still crashing.
Of course I didn't try all the various settings.
But let me know if you want the ADF/DMS for testing.

Thanks for the blast from the past :)
fuszy / T.E.K.

**Comment by dirkwhoffmann** [comment]
> But let me know if you want the ADF/DMS for testing.

Yes please. It'll be fun to see how the emulator reacts. Emulation of drive sound is very simple, so I am pretty sure it won't match what we get on the real machine. Anyway, let's give it a try.

**Comment by tcurdt** [comment]
> > But let me know if you want the ADF/DMS for testing.
> Yes please. It'll be fun to see how the emulator reacts. 

Alright!

https://vafer.org/shared/B580516A-7BBF-4887-A504-EAAF238D5C86/rampage.adf

> Emulation of drive sound is very simple, so I am pretty sure it won't match what we get on the real machine. 

But it is a nice detail on your part. Love it :)

**Comment by dirkwhoffmann** [comment]
Very cool demo!!

vAmiga freezes at the beginning of this scene:

<img width="976" alt="Bildschirmfoto 2022-01-31 um 07 14 10" src="https://user-images.githubusercontent.com/12561945/151747345-87276398-8417-4cbf-99ee-07fbf2bc266a.png">

For some reason, the CPU is sent into no man's land:

<img width="980" alt="Bildschirmfoto 2022-01-31 um 07 13 47" src="https://user-images.githubusercontent.com/12561945/151747391-aa241d4d-9c4f-448a-8ea8-7119592d5d23.png">

Works fine in WinUAE 4.9.0:

<img width="720" alt="Bildschirmfoto 2022-01-31 um 07 12 47" src="https://user-images.githubusercontent.com/12561945/151747515-af54bc03-367f-4582-8ea5-dee71d9bba28.png">

@tcurdt: Do separate executables for the different demo scenes exist? I.e., is it possible to run the desert scene without running the preceding parts? Since the bug happens so late in the demo, it's extremely hard to debug.

**Comment by tcurdt** [comment]
> Very cool demo!!

Thanks :)

> vAmiga freezes at the beginning of this scene:

Exactly

> For some reason, the CPU is sent into no man's land:

Unfortunately I am not the author of that exact part.
But I think it was another part or the switch to it that caused the problem.

I found an old UAE conversation about this problem:


> The problem is a copper list at 0x38108

> 000381b0: 0102 00cc             ; BPLCON1 := 0x00cc
> 000381b4: ff01 ffff             ; Skip if vpos >= 0xff and hpos >= >0x00.
>                                 ; VP ff, VE 7f; HP 00, HE fe; BFD 1
> 000381b8: 0088 0000             ; COPJMP1 := 0x0000
> 
> VPOS advances to 0x100 from 0xff here
> 
> 000381bc: 8033 80fe             ; Wait for vpos & 0x00 >= 0x80 and
p os >>= 0x32.
>                                 ; VP 80, VE 00; HP 32, HE fe; BFD 1
> 
> Because VPOS is 0x100, this comparison can't be ever true and copper never advances
> past this wait and always "loops" back to 0x38108 (COP1LC points there)
> 
> 000381c0: 0102 00cc             ; BPLCON1 := 0x00cc

> Apparently UAE assumes wrong timing assumptions for the transition of the raster beam from 0xff to 0x100.

Hopefully this will give some clues.

> Do separate executables for the different demo scenes exist? I.e., is it possible to run the desert scene without running the preceding parts? Since the bug happens so late in the demo, it's extremely hard to debug.

We all worked on the separate parts in teams or individually and then had a scheduler that combines them in the trackmo.
But I only still have the source code of the parts I wrote solo.

So I fear there is no (easy) way of shortening this. Especially as the problem is probably related to part switching.
In theory you should be able skip parts by modifying the internal manager scripts that do the coordination.
In the good old days I would have used the action replay module for that.

Not sure that really helps - but you can find some of that at the top of the parts. 

https://github.com/tcurdt/rampage

**Comment by dirkwhoffmann** [comment]
> Hopefully this will give some clues.

Definitely!! I'll try to convert the Copper list shown above into test cases that fail in vAmiga. Issue #629 is also related to the Copper crossing from $FF to $00. So, there is definitely something wrong in the current Copper implementation.

**Comment by dirkwhoffmann** [comment]
I see. Yes, when running vAmiga with debug option `BLT_GUARD = 1`, it detects the issues (the sequence in which the freeze happens starts around frame 4000) :

```
[2956] (  0, 12) 028DA2  1 BCBSDA 6004 17E6 Blitter:483 BLTPRI changed while Blitter is running
[4037] (  9, 89) 038C68  3 BCBSDA 6044 17E2 Blitter:180 BLTBPTH written while Blitter is running
[4037] (  9, 91) 038C68  3 BCBSDA 6044 17E2 Blitter:196 BLTBPTL written while Blitter is running
[4037] (  9,103) 038C72  3 BCBSDA 6044 17E2 Blitter:152 BLTAPTH written while Blitter is running
[4037] (  9,105) 038C72  3 BCBSDA 6044 17E2 Blitter:168 BLTAPTL written while Blitter is running
[4037] (  9,117) 038C7C  3 BCBSDA 6044 17E2 Blitter:236 BLTDPTH written while Blitter is running
[4037] (  9,119) 038C7C  3 BCBSDA 6044 17E2 Blitter:252 BLTDPTL written while Blitter is running
[4037] (  9,127) 038C86  3 BCBSDA 6044 17E2 Blitter:390 BLTBMOD written while Blitter is running
[4037] (  9,129) 038C86  3 BCBSDA 6044 17E2 Blitter:379 BLTAMOD written while Blitter is running
[4037] (  9,133) 038C8C  3 BCBSDA 6044 17E2 Blitter:379 BLTAMOD written while Blitter is running
[4037] (  9,135) 038C8C  3 BCBSDA 6044 17E2 Blitter:390 BLTBMOD written while Blitter is running
[4037] (  9,147) 038C8C  3 BCBSDA 6044 17E2 Blitter:26 BLTCON0 written while Blitter is running
[4037] (  9,149) 038C96  3 BCBSDA 6044 17E2 Blitter:102 BLTCON1 written while Blitter is running
[4037] (  9,197) 038C9E  0 BCBSDA 6044 17A2 Blitter:301 BLTSIZE written while Blitter is running
```

At the moment, I cannot do anything about it, because my current Blitter implementation can't handle on-the-fly register modifications. Maybe I'll integrate an "Accuracy level 4 Blitter" at a later point in time which will emulate the Blitter according the Alice schematics. However, there are bigger fish to fry at the moment, so can't tell if or when this is going to happen.
