### ISSUE TITLE
Overclocked CPU

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#661]
Requested by @chris70c

> would it be possible in the future to have an overclocked version of the cpu in vAmiga (like a 14MHz 68K for example)?

It should be fairly easy to implement a 14MHz and a 28MHz variant. Could be a nice v2.1 feature...

**Comment by mras0** [comment]
FYI WinUAE supports CPU frequency scaling from -90% to +500% in increments of 10%. I support integer multiples of [1;22] * 7Mhz clock in my emulator (>22 won't boot), since that was easy (I just do custom chip updates every 1/N cpu cycle). I'm not quite sure how the synchronization is done in vAmiga, but if you're implementing this you may want to consider implementing it generally (i.e. not limiting yourself to *2 and *4), even if you don't expose such options in the user friendly GUI.

Having e.g. 10x speed if you're testing a system friendly program (from HD w/ fast RAM configured) can be useful (even if just means seeing the comment in SysInfo regarding your CPU sepeed :) ).

**Comment by dirkwhoffmann** [comment]
> I support integer multiples of [1;22] * 7Mhz clock in my emulator

I think I should be able to do the same. In vAmiga, everything is tight to the master clock which runs at 28MHz (like on a real Amiga). By increasing the master clock frequency, I could achieve larger factors than 4. It should be possible to use multiples of 3.15MHz, because the 68000 is practically running at this speed (this is because the smallest atomic operation of the 68000 consumes 2 cycles, so we can consider 2 cycles as being a single atomic step). This can be seen nicely in the Moira code which is full of `sync(<delay>)` statements. The smallest value for `<delay>` is 2 and the total number of cycles is an even number for all instructions.

**Comment by emoon** [comment]
Two things that springs to mind.

SysInfo https://sysinfo.d0.se and this game https://en.wikipedia.org/wiki/Frontier:_Elite_II 

The reason I'm recommending the game is that (if I remember correct) the game uses the CPU to render the (filled) graphics so a faster CPU should make the frame rate of the game better. It's really slugish on a stock 68000

**Comment by dirkwhoffmann** [comment]
Sysinfo with 8x overclocking:

<img width="1146" alt="Bildschirmfoto 2022-05-13 um 19 04 58" src="https://user-images.githubusercontent.com/12561945/168334635-32cb09c5-6130-4a10-b379-33b7329e3871.png">

Frontier ist a brilliant test case. With 8x overclocking, it's really smooth 😎:

<img width="1146" alt="Bildschirmfoto 2022-05-13 um 18 56 51" src="https://user-images.githubusercontent.com/12561945/168334729-04a20008-6b95-4fe4-92d7-58af9a65d0a9.png">

However, I am experiencing some strange graphics artefacts when booting with Kickstart 2.04:

<img width="1146" alt="Bildschirmfoto 2022-05-13 um 19 01 34" src="https://user-images.githubusercontent.com/12561945/168334852-08ec994e-7d9e-4078-bc38-e20a846af096.png">

The artefacts are less with acceleration factor 5 and they vanish with factor 4. In UAE, I don't see these glitches, but I have no idea how overclocking is emulated there. E.g., when using the FastBlitter in vAmiga (level 0), everything looks fine.

**Comment by mras0** [comment]
FWIW SysInfo also shows 60MHz for me w/ 8x CPU speed (44.20 if no fast RAM is present). It doesn't quite match what I get from WinUAE if I try to replicate the same setup there. Since I only use it when I've wanted something to run fast, I haven't really done much "proper testing".

I don't get any graphic glitches with the v2.04 boot screen though, and I'm doing what I outlined above (i.e. roughly your approach). Are you seeing any writes to BLTSIZE while the blitter is active (I get one benign write very early for a 1x1 blit w/ 4x+ acceleration)?

Another thing is that you may run into correctness issues with agnus.executeUntilBusIsFree() being called while penalty > 0 (like I wrote earlier in the thread), but I'm not sure.

**Comment by mras0** [comment]
I can also see that there's an issue in KS1.x with drawing of the title bar:
![image](https://user-images.githubusercontent.com/9952017/168420556-aac7dd96-7f52-4773-a437-b3445f5714f2.png)

Obviously the "fix" i outlined in my edit isn't the proper solution, but there seems to be something wrong with the CPU <-> custom chip synchronization.

I've made a small test program to test the access speed:
[memspeed.zip](https://github.com/dirkwhoffmann/vAmiga/files/8692663/memspeed.zip) and I can see that access to chip+custom memory is too fast in vAmiga with just the above change.

Here are numbers from WinUAE (512K chip + 2MB fast config).

| Frequency multiplier | CIA  | Chip | Custom | ROM  | Fast |
|----------------------|------|------|--------|------|------|
| 1x                   | 2820 | 1333 | 1333   | 1333 | 1333 |
| 2x                   | 1410 | 853  | 853    | 564  | 564  |
| 4x                   | 1410 | 710  | 710    | 282  | 282  |
| 8x                   | 1410 | 529  | 629    | 123  | 123  |
| 10x                  | 1410 | 617  | 617    | 101  | 101  |

**Comment by dirkwhoffmann** [comment]
> I've made a small test program to test the access speed

Amazing! I am pretty busy over the weekend, but I'll try that out asap.

**Comment by dirkwhoffmann** [comment]
In my debug log, I've spotted this with 8x speed:

```
[14] (221, 39) FA8878  0 ----D- 600C 0020 Blitter:94 pokeBLTCON1(0)
[14] (221, 40) FA887E  0 ----D- 600C 0020 Blitter:293 pokeBLTSIZE(41)
```
There are custom chip writes in two consecutive cycles (39 and 40). This is impossible on a real machine, even if opcodes are fetched from Fast Ram.

I think the problem is this: Currently when accessing ChipRam, the CPU syncs with Agnus first (this is what @mras0 mentioned above): 

```C++
void
Agnus::executeUntilBusIsFree()
{
    if (cpu.penalty) {
        execute();
        cpu.penalty = 0;
    }
    ...

```
Now, let's assume that the CPU continues with a Fast Ram access. In this case  the CPU would perform the access in the very same DMA cycle which is wrong. On a real machine, the CPU would have to hold the address and data lines for the whole DMA cycle. This means that a penalty has to be added which corresponds to a complete DMA cycle. Maybe something like this:

```C++
   if (cpu.penalty) {
        execute();
    }
    cpu.penalty = 2 * cpu.overclocking;
```

 Tomorrow, I'll investigate this further...

**Comment by mras0** [comment]
Some info about the test prorgam: It disables DMA and interrupts and then runs an unrolled loop of 1000 `tst.b (a0)` 10 times.

TST.B (An) takes 8 cycles: 4 cycles to do the read from (An) follow by 4 cycles for prefecting the next instruction.

1x timing makes perfect sense, all memory accesses take at least 4 CPU cycles so timing is the same (except for CIA where it's not fast enough to do back-to-back accesses => frequency is Eclock/2).

8x/10x weren't well supported by WinUAE. I had to manually type a number and the numbers don't quite add up, so lets ignore those.

For 2x and 4x fast ram access time is also easily explained: It takes 8 CPU cycles (because code is also running from fast RAM).  For custom/chip access there's [this EAB thread](https://eab.abime.net/showthread.php?t=98125) explaining why it'll always take at least 2 CCKs (in particular post #7 by Toni).
I can figure out why the timing for the 2x case makes sense: 1 CCK (=4 CPU cycles) sync time, 1 CCK access time and then 1 CCK to do prefetch (not synced with chipset). Aligns nicely and access interval of 853ns/12 is pretty close to 1/CPU frequency.

4x is a bit more puzzling. If chip/custom access can only start aligned with CCKs I'd expect it to take 24 cycles: 1 CCK (=8 CPU cycles) to sync, 1 CCK for access, 1/2 CCK for prefetch and then 1/2 CCK to align again. The ~20 cycles I get experimentally seems to indicate that the 1/2 CCK alignment part (=4 CPU cycles) maybe isn't needed according to WinUAE?

I'll try to do some more digging to figure out what I'm missing.

BTW I think your ACA500+ board should allow verification of at least 2x speed (maybe also 3x and 4x with overclocking, but I don't know if that's advisable)

**Comment by dirkwhoffmann** [comment]
Some results with the ACA500+ 😎:

7MHz CPU:
![IMG_2744](https://user-images.githubusercontent.com/12561945/168457708-b0614ef4-b100-411e-bd82-1602ba0e1195.JPG)

14MHz CPU:
![IMG_2747](https://user-images.githubusercontent.com/12561945/168457723-1eb4c1c8-5fe0-4a75-b38d-9a44bef6bf80.JPG)

21MHz CPU:
![IMG_2748](https://user-images.githubusercontent.com/12561945/168457966-bac04e39-c1b1-42f0-ae8f-82c9ba6f8eba.JPG)

28MHz CPU:
![IMG_2749](https://user-images.githubusercontent.com/12561945/168457971-91267999-4106-42b5-8af3-c4a2513a1f99.JPG)

42MHz CPU:
![IMG_2750](https://user-images.githubusercontent.com/12561945/168457975-a72e7e7e-d557-46aa-844f-bc074ce1ce51.JPG)

Interestingly, `memspeed.exe` only reports 31MHz in 42MHz mode.

**Comment by dirkwhoffmann** [comment]
Update: 

SysInfo in 28MHz mode:
![IMG_2756](https://user-images.githubusercontent.com/12561945/168458385-77dbd8c9-d725-456a-a1c7-2a53e3f917de.JPG)

SysInfo in 42MHz mode:
![IMG_2757](https://user-images.githubusercontent.com/12561945/168458389-6ce6852e-4116-46d2-a5d4-b2b550c8b368.JPG)

**Comment by mras0** [comment]
Great! So at least for the ACA500 my understanding was correct and chip/custom access tops out at 3 CCKs. That's much easier to emulate than trying to match whatever WinUAE is doing, and makes more sense IMO.

So from a functional point of view something like this happens:
1. CPU waits until start of next bus cycle
2. CPU transfers address to Agnus (takes one bus cycle)
3. CPU waits until bus is free (zero or more bus cycles)
4. Transfer happens (takes one bus cycle)

At 7MHz step 1 is never needed since the CPU is always in sync with the bus (color) clock, and one bus cycle = 2 CPU cycles making things easy. At e.g. 28MHz the back to back tst.b's execute like this:
```
CPU CCK
0   0       Address transfer to agnus
1   0       ..
2   0       ..
3   0       ..
4   0       ..
5   0       ..
6   0       ..
7   0       ..
8   1       Chip ram access
9   1       ..
10  1       ..
11  1       ..
12  1       ..
13  1       ..
14  1       ..
15  1       ..
16  2       Start of fast ram access
17  2       ..
18  2       Prefetch
19  2       ..
20  2       Wait for next bus cycle
21  2       ..
22  2       ..
23  2       ..
24  3       Address transfer to agnus (next instruction)
```

Looking at the vAmiga source code that might not be so easy to cleanly emulate, but it might be possible to keep the ugly bits confined to executeUntilBusIsFree.

> Interestingly, memspeed.exe only reports 31MHz in 42MHz mode.

The reported CPU frequency is based on the assumption that each tst.b instruction executes in 8 cycles, i.e. the 258ns access time (which includes both prefetch and actual memory access) => 8 cycles * 1e9 (ns/sec) / 258ns = 31.007Mhz. If I'm reading this [info about the ACA500plus](http://wiki.icomp.de/wiki/ACA500plus_registers#ACA500plus_version_ID_and_clock_control) correctly it can't access memory at full speed when running at 42Mhz which would explain it.

Or it could just be that the test program is buggy. It was thrown together rather quickly :)

**Comment by dirkwhoffmann** [comment]
OK, this is how close I came today: 

<img width="1050" alt="Bildschirmfoto 2022-05-15 um 18 33 59" src="https://user-images.githubusercontent.com/12561945/168483635-e7e277f2-3911-45c5-9c32-024d2c3888bd.png">

The slow Ram discrepancy is due to the ACA as it emulates trapdoor Ram as fast Ram. 

The CIA discrepancy is due to my EClock which still runs at 1/10th of the native 7MHz clock signal. I need to add some additional syncWithEClock function for the overclocking case. 

Unfortunately, emulation is not really accurate. I kind of fake the two color cycle delay at the moment:

```C++
void
Moira::sync(int cycles)
{
    CPU *cpu = (CPU *)this;

    if (!cpu->config.overclocking) {

        // Advance the CPU clock
        clock += cycles;

        // Emulate Agnus up to the same cycle
        agnus.execute(CPU_AS_DMA_CYCLES(cycles));

    } else {

        // Consume some cycles if the CPU owns the bus
        if (agnus.busOwner[agnus.pos.h] == BUS_CPU) {

            clock += 2;
            agnus.execute();
            clock += 2;
            agnus.execute();
            cpu->penalty = 0;
        }

        cpu->penalty += cycles;

        while (cpu->penalty >= 2 * cpu->config.overclocking) {

            // Advance the CPU clock by one DMA cycle
            clock += 2;

            // Emulate Agnus for one DMA cycle
            agnus.execute();

            cpu->penalty -= 2 * cpu->config.overclocking;
        }
    }
}
```

**Comment by mras0** [comment]
Seems like decent progress to me. Even if it isn't completely accurate, it'll probably be fine for the intended use case: Making games run faster (it's not like there are any demos that require cycle exact 21MHz 68000).

I've looked more into why WinUAE behaves differently, and I think it's wrong in this case (will report later). It seems to operate more or less on the same principle and the "penalty" carries over when it's less than a CCK (so it converges towards 2CCKs for this test). Since nobody's complained about that before it should be safe to postpone major changes until a much later version.

Also think I'll rework the test a bit, so other corner cases can be tried (e.g. long word access).

Regarding CIA access, I had a look at Agnus::executeUntilBusIsFreeForCIA - I don't think CIA requires chip bus to be free. Should be easy enough to verify. Quick sketch: run blitter with minterm that uses all cycles while cpu accesses CIA, even with code in chip ram it should run faster if CIA access can happen independently. I can try to cook up a test for that as well.

**Comment by dirkwhoffmann** [comment]
I've made some progress. Here are the results with the latest code on the dev branch:

<img width="936" alt="Bildschirmfoto 2022-05-17 um 07 52 22" src="https://user-images.githubusercontent.com/12561945/168739383-44dfd05e-d287-4f84-9c4e-e79c454b3eb8.png">

<img width="936" alt="Bildschirmfoto 2022-05-17 um 07 52 51" src="https://user-images.githubusercontent.com/12561945/168739401-cb119fbc-dda0-4e4d-a191-5360ac6b00ce.png">

<img width="936" alt="Bildschirmfoto 2022-05-17 um 07 53 07" src="https://user-images.githubusercontent.com/12561945/168739416-160ff57b-60af-4166-bcec-386d3ace554b.png">

14MHz and 21MHz mode are good. At 28MHz, vAmiga runs faster than the overclocked A500. 

Furthermore, overclocking is part of the GUI now:

<img width="1050" alt="Bildschirmfoto 2022-05-17 um 08 00 02" src="https://user-images.githubusercontent.com/12561945/168739951-a2c338ec-69a6-4249-b47e-ee74a9a677f4.png">

**Comment by dirkwhoffmann** [comment]
> Also think I'll rework the test a bit, so other corner cases can be tried (e.g. long word access).

This would be great. I am really curious if the correctness of my implementation is only correct by accident in the case of 14MHz and 21MHz.

**Comment by mras0** [comment]
New tests: [memspeed2.zip](https://github.com/dirkwhoffmann/vAmiga/files/8732157/memspeed2.zip)

TST.B is the old one, TST.L tests long word access, LSR x is LSR.W Dn, Dm (with Dn=x) followed by TST.B and "FAST" is worst case MULU.W in DBF loop.

**Comment by dirkwhoffmann** [comment]
> New tests: memspeed2.zip

Great! ACA500+ results:

![IMG_2765](https://user-images.githubusercontent.com/12561945/169455730-31a833aa-9803-4f35-ad59-d4fd0d7635b6.JPG)
![IMG_2766](https://user-images.githubusercontent.com/12561945/169455737-a1162087-a46b-4b62-896f-045bad900266.JPG)
![IMG_2767](https://user-images.githubusercontent.com/12561945/169455745-85553263-4ca9-4cbe-87f5-d9b36f81989c.JPG)
![IMG_2768](https://user-images.githubusercontent.com/12561945/169455752-54cc562c-7405-4b29-bb02-0151d795bf11.JPG)
![IMG_2769](https://user-images.githubusercontent.com/12561945/169455763-28df2a76-5bc8-4085-9b60-c77a4b00afe9.JPG)

**Comment by dirkwhoffmann** [comment]
vAmiga:
<img width="1050" alt="Bildschirmfoto 2022-05-20 um 07 22 05" src="https://user-images.githubusercontent.com/12561945/169457082-032db6ac-9b0a-4894-a340-66d0cfdf8e5c.png">

<img width="1050" alt="Bildschirmfoto 2022-05-20 um 07 13 08" src="https://user-images.githubusercontent.com/12561945/169457106-f7e8b4cc-1299-4c41-81d4-0462111ff74b.png">

<img width="1050" alt="Bildschirmfoto 2022-05-20 um 07 12 48" src="https://user-images.githubusercontent.com/12561945/169457056-78c57f18-831f-4e6b-9c88-360d74c8aec1.png">

The test reveals that vAmiga is not 100% accurate, but it might be sufficient for our purpose (there is no need to be 100% exact in overclocked scenarios). 

I also tried the test in UAE, but I didn't manage to overclock the CPU. For some reason, the CPU always runs in 7MHz mode even if I configure it to run twice as fast:

<img width="1073" alt="Bildschirmfoto 2022-05-20 um 07 35 23" src="https://user-images.githubusercontent.com/12561945/169458194-ff5b74e6-764b-4ca4-af01-58a9c335f29b.png">

**Comment by mras0** [comment]
The tests confirm that the read access can start immediately if the tst instruction starts "aligned" with the CCK (e.g. LSR 4 @ 28Mhz where it only needs to waste 4 CPU cycles / 0.5 CCK every other instruction).

> also tried the test in UAE, but I didn't manage to overclock the CPU. For some reason, the CPU always runs in 7MHz mode even if I configure it to run twice as fast:

You need to enable "Cycle-exact (Full)" in Hardware->Chipset and disable slow mem (and of course enable Z2 fast if you haven't already). For some reason slow mem comes first in the memlist (in your screenshot I can see the code is running from slow mem, so you won't get full speed). Note again though, that I think WinUAE isn't quite right for CPU speeds larger than 14MHz (yet).

**Comment by dirkwhoffmann** [comment]
Because the two `memspeed` tests work so well, I've added them to the vAmigaTS repo:
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Memory/memspeed

**Comment by mras0** [comment]
Actually, looking at the LSR4 result @ 28MHz and trying to implement it on my own, I'm no longer sure I know what's really happening. Maybe the initial sync with Agnus doesn't really take a full CCK. Will try to see if I can get something that matches the experimental results, and maybe that'll spawn some more test cases.

> Because the two `memspeed` tests work so well, I've added them to the vAmigaTS repo

Feel free to add the source as well if you like (usual licenses are fine). I've compiled them with vbcc/vasm and can extract command line arguments if necessary.

**Comment by dirkwhoffmann** [comment]
I'm closing this issue for now, because the main functionality is working. Please reopen any time if a more accurate emulation is required to run a particular game or demo.
