### ISSUE TITLE
Callstack feature

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#671]
In preparation for implementing a call stack feature (needed by @prb28), I’ve added a counter which is incremented when JSR or BSR is executed and decremented on RTS. A short time after launching Kick 1.3 or Kick 2.04, the counter becomes negative. This means that either

- I am counting wrong, or
- Kickstart does some manual stack manipulation mimicking a JSR or BSR from time to time.

Does somebody know ad hoc if such a technique is used?

**Comment by mras0** [comment]
> Kickstart does some manual stack manipulation mimicking a JSR or BSR from time to time.

Not just some of the time. Every call to dos.library in KS1.3 goes through this function:
```
00ff4134  265f                      MOVEA.L     (A7)+, A3
00ff4136  48f1 1a00 08f4            MOVEM.L     A1/A3-A4, $-0c(A1,D0.L)
00ff413c  d3c0                      ADDA.L      D0, A1
00ff413e  48d1 001e                 MOVEM.L     D1-D4, (A1)
00ff4142  4ed4                      JMP         (A4)
```

And when it returns:
```
00ff4128  4ce9 0a00 fff4            MOVEM.L     $-000c(A1), A1/A3
00ff412e  2869 fffc                 MOVEA.L     $-0004(A1), A4
00ff4132  4ed3                      JMP         (A3)
```

And exec.library/Supervisor (A5 contains a function pointer):
```
Supervisor                      	; $00fc08e6
	OR.W	#$2000, SR
	PEA.L	SuperReturn
	MOVE.W	SR, -(A7)
	JMP	(A5)
SuperReturn
	RTS
; ....
PrivilegeViolationHandler       	; $00fc090e
	CMP.L	#Supervisor, $0002(A7)
	BEQ.B	.IsSupervisor
	CMP.L	#Supervisor68010, $0002(A7)
	BNE.B	.RealError
.IsSupervisor
	MOVE.L	#SuperReturn, $0002(A7)
	JMP	(A5)
```

Not to mention interrupts, stack swapping and task switching.

Depending on the actual requirements, you may be able to get an acceptable result by walking the stack, and filtering out obvious stuff (odd address, not within program bounds, etc.), but be aware that intermediary functions (probably only ones written in assembly) may push plain (16-bit) words on the stack, though it should be rare.

**Comment by dirkwhoffmann** [comment]
OMG 🙈. I knew that recording a call stack is an impossible mission for the C64, but I didn't expect it so difficult for the Amiga. 

> you may be able to get an acceptable result by walking the stack

This would give me a trace for the PC only, but @prb28 needs the contents of all registers at the time of the jump. My plan was to put the registers contents into a ring buffer when `JSR` or `BSR` is executed and to remove an element in the instruction handler of `RTS`. Apparently, this turns out to be too simple.

**Comment by dirkwhoffmann** [comment]
@prb28 Callstack recording is (somewhat) available.

@mras0 had clever ideas about callstack recording. However, because there is tons of other stuff to do, I’ve decided to start with the simple ring buffer approach that pushes an entry for each `JSR` and `BSR` instruction and pops an entry for each `RTS`. If an `RTS`hits an empty buffer, it is ignored. The approach is very simple, but it might be sufficient for most use cases. To see how the callstack buffer can be accessed, please have a look at the following RetroShell command handler: 

    RetroShell::exec <Token::cpu, Token::callstack> (Arguments &argv, long param)

Important: Callstack recording requires the Amiga to run in debug mode. Debug mode can be controlled via the following functions in the Amiga class: 

    bool inDebugMode() const;
    void debugOn();
    void debugOff();

**Comment by dirkwhoffmann** [comment]
Part of v2.0b2 which is now online.

**Comment by emoon** [comment]
Slightly on/off-topic :)

I worked on something similar in the past for PS2 where figuring out a callstack is quite difficult as well. It should be noted as this was on original hardware so I couldn't just "trap" jumps and such.

1. Figure out the range where the code lives (i.e RO-sections in executable and where they are "mapped" in memory)
2. I would then walk the stack looking at the data there. I would look for addresses/values that matches the addresses mapped to memory/code section.
3. Build callstack from these values.

This actually works quite well. Now, I'm not sure if it's useful in the case above as you have a bit more control due to trapping instructions, but thought I would post it anyway :)

**Comment by emoon** [comment]
Slightly on/off-topic :)

I worked on something similar in the past for PS2 where figuring out a callstack is quite difficult as well. It should be noted as this was on original hardware so I couldn't just "trap" jumps and such.

1. Figure out the range where the code lives (i.e RO-sections in executable and where they are "mapped" in memory)
2. I would then walk the stack looking at the data there. I would look for addresses/values that matches the addresses mapped to memory/code section.
3. Build callstack from these values.

This actually works quite well. Now, I'm not sure if it's useful in the case above as you have a bit more control due to trapping instructions, but thought I would post it anyway :)
