### ISSUE TITLE
2.0b2 Instant crash on launch

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#679]
Instant crash on launch with 2.0b2 on an M1 Pro. 

Edit: Should probably mention I'm on macOS 12.3.1

**Comment by dirkwhoffmann** [comment]
Bummer! Unfortunately, I can't debug it myself, because my M1 machine still has not been delivered 😕.

**Comment by rjpontefract** [comment]
The crash on startup may be related to this, as it also crashes for me:

022-04-10 18:45:09.852334+1200 vAmiga[61793:3817405] Swift/x86_64-apple-macos.swiftinterface:32547: Fatal error: Double value cannot be converted to Int because it is either infinite or NaN

It's in this part of the code:

var autofireFrequency = ControlsDefaults.std.autofireFrequency {
        didSet {
            let autofireDelay = Int(50.0 / autofireFrequency)

autofireFrequency is 0.

**Comment by dirkwhoffmann** [comment]
> The crash on startup may be related to this

Thanks! So it seems like an issue with invalid values in the user default storage. The emulator needs to check for an inconsistent value in this case. I'll change that...

**Comment by dirkwhoffmann** [comment]
Hopefully fixed in v2.0b3.

**Comment by shinra-electric** [comment]
Can confirm fixed in 2.0b3, but there is another problem. I'll open a new issue.
