### ISSUE TITLE
vAmiga does not locate rom images - 2.0b3 (possibly 2.0b2)

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#680]
Opening 2.0b1 and the kickstarter ROM loads fine: 
![Screenshot 2022-04-10 at 11 04 47](https://user-images.githubusercontent.com/50119606/162613097-f8a0d769-8936-48a5-be3a-9284051ca07e.png)

Opening 2.0b3 and vAmiga asks for the ROM images: 
![Screenshot 2022-04-10 at 11 04 20](https://user-images.githubusercontent.com/50119606/162613108-2811fb67-d9b5-41d5-b335-2596fcf1c17e.png)

This issue could have been introduced with 2.0b2, but since that didn't work on the M1 I can't test. 

I'm on an M1 and macOS 12.3.1

**Comment by dirkwhoffmann** [comment]
Ah, OK, I think I know what the issue is. Since v2.0b2, vAmiga is a sandboxed app. For sandboxed apps, the location of the user defaults directory is different which means that vAmiga doesn't find your settings. 

What you need to do is to reconfigure everything (😬). I.e., install the Rom manually and click "Use as Default". The same holds for all other settings that diverge from the default values.

**Comment by shinra-electric** [comment]
I'll try what you suggested, but my roms are in `~/Library/Application Support/vAmiga/Kickstart Roms/` 

I would have thought that this would be the default place for the app to look on startup..?

**Comment by dirkwhoffmann** [comment]
> I would have thought that this would be the default place for the app to look on startup..?

It depends whether a macOS app is sandboxed or not. E.g., here are the two paths used by macOS on my machine:

    /Users/hoff/Library/Application Support/vAmiga
    /Users/hoff/Library/Containers/dirkwhoffmann.vAmiga/Data/Library/Application Support/vAmiga

The second one is used when the app is run as a sandboxed app. In this case, macOS uses different directories, because access to a large portion of the file system is blocked.

BTW, I've also experienced a situation today where all user settings were read as 0 on startup. It must have been the same situation as the one causing the crash with `autofireDelay` being zero. Unfortunately, I haven't found a way to reproduce it reliably. After I started to debug the issue, the phenomenon disappeared.

**Comment by shinra-electric** [comment]
I've dropped the 1.3 kickstart into the window. 

I know you said to click "Use as default" in order for it to remember the selection, but in my opinion if there is no rom already set as the default, it vAmiga should automatically set the first rom dropped onto the window as the default. (If the user wants to change the default, they can drag then a new rom and click "use as default"). 

Anyway, it seems to remember the rom now, so I'll close this issue. 

But there is a new issue that you can look forward to.... 😅
