### ISSUE TITLE
TEK - Rampage issues

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#708]
[Pouet link](https://www.pouet.net/prod.php?which=6476) ADF: [TekRampage.zip](https://github.com/dirkwhoffmann/vAmiga/files/8855762/TekRampage.zip)

- Looks like the sliding TEK logo might have missing some blocks (not sure if this is in the real vAmiga, see screenshot below).
- Crashes in "spaceship part"

Works in WinUAE 4.9.1 with classic A500 quickstart (KS1.3/512K chip/512K slow) and on my real A1200. Note that I tested it because it was mentioned in the ["Problematic Demos"](https://eab.abime.net/showthread.php?p=1548987#post1548987) thread on EAB (probably for a good reason).

![image](https://user-images.githubusercontent.com/9952017/172457535-fe8e7842-5ad0-4bac-ba67-1271fc8ba13c.png)

Just tested a few configs (including vAmigaWeb) and issues are the same. (It also crashes in my emulator, but haven't debugged it).

**Comment by dirkwhoffmann** [comment]
Amazing. Seems like the whole screen is drawn by the Copper. 

<img width="1076" alt="Bildschirmfoto 2022-06-07 um 21 35 07" src="https://user-images.githubusercontent.com/12561945/172467658-ed42dafc-73c7-401a-85eb-20735d0fdca9.png">

**Comment by dirkwhoffmann** [comment]
I think the graphics glitch is not a bug. It is also visible in UAE if the screen geometry is switched to "Extreme" (just notices that I am still running 4.9.0, need to check if this makes a difference...):

<img width="968" alt="Bildschirmfoto 2022-06-08 um 16 06 35" src="https://user-images.githubusercontent.com/12561945/172637945-bac1dc3e-1fc5-4ea0-95c9-a3ab26f8225c.png">

On my A500, there is no visible glitch, because the erroneous stripe is outside the visible area. If vAmiga is run with the same screen geometry as my TFT, it looks just fine, too. 

BTW, I've written a bunch of [new test cases](https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON1) that verify BPLCON1 behaviour in the overscan area (`overscan1` - `overscan6`, `overscan1b` - `overscan6b`).

**Comment by mras0** [comment]
Very interesting, so actual time is (probably) even longer? Of course, the issue might be different in vAmiga, but since I got this debug output if figured it was very close:
```
[4038] (  9,200) 038C9E  0 BCBSDA 6044 17A2 XFILES: Overwriting existing Blitter event
[4038] ( 13, 32) 00001C  6 BCBSDA 6044 37A2 XFILES: lineFException(ffff)
```

Looked at the IPL timing of `SUBI.W #...,Dn` in WinUAE and IPL fetch happens before prefetch which is why I guessed that the issue was interrupt triggering too late.

I didn't figure I needed any elaborate sync for the test, since I just wanted VERTB set in INTREQ (of course could have just set it myself or something similar) and thought only time from INTENA write to interrupt mattered.

**Comment by dirkwhoffmann** [comment]
> Made a quick test.

You've implemented an interesting test case here. I've written some INTENA / INTREQ ([enatim1 - enatim4](https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Interrupts/inttim)) tests for which I thought they would catch everything your test catches, but they don't. 

A major difference is that my tests utilise the Copper to write into INTENA / INTREQ. Needs more investigation later this week... 

I haven't found any IPLissue w.r.t the SUB instruction either. I've modified the existing IPL/ADD1.w test by replacing all ADDs with SUBs. As expected, the test image remained the same. Bottom. line: There is no difference between ADD and SUB.

**Comment by dirkwhoffmann** [comment]
> I didn't figure I needed any elaborate sync for the test, since I just wanted VERTB set in INTREQ 

If I remember correctly, the VERTB interrupt is signalled at (0,0). There is memory refresh DMA going on in cycles 1,3,5 which might possibly interfere. I am not sure if this could really make the test case indeterministic, but it might be safer to run the code sequence in the middle of the scanline.

**Comment by dirkwhoffmann** [comment]
I've written two more tests which basically mimic the INTENA test written by @mras0 (enabling IRQ by letting the CPU write into `INTENA` and running a `MOVE reg,reg` chain afterwards).

Despite some strange OCS / ECS difference (see #709), vAmiga does it right (it matches the ECS output pixel by pixel).

After running out of options, I decided to run the mras-test again on both of my stock ECS and OCS machines. On these machines, I get a different result. The winner is "blue" on both:

![IMG_2885](https://user-images.githubusercontent.com/12561945/172793588-08711138-ea9c-49dd-9a44-9f7a1ff7c9d4.JPG)

Summary:
- A500 with ACA500plus: Cyan
- Stock A500 ECS: Blue
- Stock A500 OCS: Blue

**Comment by dirkwhoffmann** [comment]
More findings: I tried to run IPL test `IPL/S/SUB1w.adf` in UAE. For whatever reason, the ADF does not boot. If `include "ministartup.s"` is commented out, it boots. However, it's completely off. My CPU sync code does not manage to stabilise the CPU in UAE which results in a flickering image. Here is a still:

<img width="719" alt="Bildschirmfoto 2022-06-09 um 13 31 47" src="https://user-images.githubusercontent.com/12561945/172837622-7a3f76f9-0bac-4d2e-b7e0-b07d801b5c1f.png">

vAmiga: 

<img width="1076" alt="Bildschirmfoto 2022-06-09 um 13 53 44" src="https://user-images.githubusercontent.com/12561945/172840686-94ea0dd8-8dee-473c-8041-b3d071ab3a75.png">

This is the reference image (A500 OCS):

![SUB1w_A500_OCS](https://user-images.githubusercontent.com/12561945/172837707-553a5e2a-9bbb-4792-a144-b5322f60380b.JPG)

The discrepancies mean that UAE either uses wrong IPL timing for the SUB command or the mismatch is due to a more general interrupt timing issue. 

Putting all together, there is another hypothesis we might have to consider: Maybe vAmiga does the right thing (i.e., modifying a Blitter register while the Blitter is active) and crashes because it does not handle this case correctly.

**Comment by mras0** [comment]
IPL/S/SUB1w.adf is stable in 4.9.1 with A500 "Most common" configuration for me. Config I'm using:[a500.zip](https://github.com/dirkwhoffmann/vAmiga/files/8871923/a500.zip)

Looks like this:

![image](https://user-images.githubusercontent.com/9952017/172890374-9cb9c7d7-2488-472c-8cba-61b0d72fe58d.png)

In latest (unstable) beta:
![image](https://user-images.githubusercontent.com/9952017/172890812-b03ea7c9-dcad-42d4-9522-d7637bfbe1b5.png)

**Comment by dirkwhoffmann** [comment]
> Sorry for the wild goose chases!

That's totally fine. Although there was no bug to fix, it was worth debugging. Firstly, the test suite grew by a few more tests which is good. Secondly, by reviewing my own code, I've seen that I need to verify the timing of the Copper COPJMP instruction. Thirdly, I've levelled up by peeking into your test cases. E.g., I wasn't aware that there is a `rep` command which allows me to shorten my assembler sources quite a bit in future.
