### ISSUE TITLE
New cputester test cases

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#732]
After passing the first quality gate (making the new CPU cores compatible with Musashi), it's time to run more sophisticated tests. For this purpose, I've created a new section in the vAmigaTS repo:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/cputester/HDF

At the moment, the directory contains one large HDF (`simple.hdf`) containing various tests created with `cputester`.  Only basic properties are tested at the moment:

```
test_rounds=2
feature_sr_mask=0x0000
feature_undefined_ccr=1
mode=all
```

The HDF contains test data for all three CPU models (68000, 68010, 68020).  To run the tests, type 

    cputest all 

when the CLI prompt comes up. `cputest` automatically detects the installed CPU, so there is not much to configure (except 8MB of FastRam).

Luckily, all tests pass when a 68000 is selected which indicates that my latest CPU changes didn't break too much old functionality. For the 68010  and 68020, errors show up almost immediately. Here is the first mismatch for the 68010 🙈:

<img width="987" alt="Bildschirmfoto 2022-08-17 um 15 28 22" src="https://user-images.githubusercontent.com/12561945/185172177-3b0a988b-4d47-4566-bc60-761b7336f6fd.png">

**Comment by mras0** [comment]
> Unfortunately, I've never managed to compile UAE in my VM.

Off-topic in the EC030 thread, so replying here just in case you want to be able to build WinUAE, but be aware that I think the cputestgen doesn't always work with the latest version of the code (it doesn't compile out of the box right now for example), which I why I think sticking with an older version is probably best.

I can build WinUAE with the latest version of Visual Studio (2022, 17.3.1). You need to follow the list steps listed in the README (substituting 2017->2022 should be fine in step 2, some extra things may need to be installed, but I don't think so) up to and including step 7 (note that the abime.net links may not work if you click directly). I have the source code checked out in `c:\dev\winuae` and have a script to build (instead of doing the last steps manually). The "subst" part at the start is because I don't have a "D:" drive.
```
@echo off
setlocal
subst d: /d
subst d: c:\dev\out
call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
set PRJ_PATH=%~dp0\WinUAE\od-win32\
set BUILD_OPTS=-nologo -verbosity:minimal
set WIN32_OPTS=%BUILD_OPTS% -property:Platform=Win32 -property:Configuration=Release
set CONFIG=Test

for %%p in (build68k_msvc genlinetoscr_msvc genblitter_msvc gencpu_msvc gencomp_msvc prowizard unpackers) do (
    echo.
    echo Building %%p
    echo.
    msbuild %WIN32_OPTS% %PRJ_PATH%\%%p\%%p.vcxproj || exit /b 1
    echo %%p
)

msbuild %BUILD_OPTS% -property:Platform=Win32 -property:Configuration=%CONFIG% %PRJ_PATH%\winuae_msvc15\winuae_msvc.vcxproj || exit /b 1
```

If it doesn't work, let me know the error and I'm sure we can figure it out.

**Comment by dirkwhoffmann** [comment]
I think Windows simply hates me because I get almost nothing to work on this platform. Not even standard stuff like updating my Visual Studio installation:

<img width="404" alt="Bildschirmfoto 2022-08-21 um 16 02 11" src="https://user-images.githubusercontent.com/12561945/185794820-a64a7ebd-6c43-4ae5-89c5-5f397abe6e9f.png">

Network is up and running. Maybe Windows senses that I hate it, too.

**Comment by mras0** [comment]
Don't recall having had that problem. One thing you can try (apart from the nuclear option of reinstalling everything) is the MS tool suggested here: https://superuser.com/a/526419
