### ISSUE TITLE
HOI game no sound in intro

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#762]
developer @rhinoid reported his hoi game https://www.proofofconcept.nl/static/hoi/hoi.zip gives no sound in intro

![D3DE51E8-C057-42FD-AF51-9CF76DD64480](https://user-images.githubusercontent.com/17108995/206518483-1b966d65-3726-4cb2-9ea6-812bb27bb76c.png)

 
here see it with sound in the intro
https://www.youtube.com/watch?v=X7f3wro8WnE

I tried different kickstarts and mem settings... no sound while in intro ... sound comes first after intro i.e. when gameplay starts

tested with embedded vAmigaCore v2.2 b1 at https://www.proofofconcept.nl/portfolio/hoi/

**Comment by mras0** [comment]
There's sound in the intro for me (Windows 11/Firefox 107.0.1) at that link. It also works in vamigaweb (ks 34.005).

**Comment by mithrendal** [comment]
@mras0 oh sorry ... have made a mistake ... the intro AFTER the pre-intro 😬 at 0:30 of the gameplay video ... sorry for the confusion

at this screen

<img width="361" alt="image" src="https://user-images.githubusercontent.com/17108995/206545107-76362559-9517-4aae-a15f-d88e3713c1fd.png">

**Comment by mras0** [comment]
What configuration is it supposed to work with? Tried it in latest WinUAE beta (4.9.9b9) and there's no sound there either (using most compatible settings KS1.3/OCS 512+512). Also tried on my A1200 (no accelerator) and it's glitchy and there isn't any sound there either. No disrespect meant to the author, I know it's hard to make something compatible when it just works on your own machine :)

**Comment by mithrendal** [comment]
that's a bummer ... on the youtube link they say that the video with the intro sound track is recorded with an emulator ... they don't say which emulator nor which ram, chipset settings / kickstart ... @mras0  me was trying also NTSC kick1.3 also without fastram ... no sound either 

@rhinoid can you remember which machine you were using when developing it

**Comment by rhinoid** [comment]
🙈.  
eeks...   I am not the one who made the disks so maybe these have never worked.  I didn't even consider this as an option.

The original disks surely did work and it worked on non-aga amiga's. Not sure if it was already tested with the 68030 kind of Amigas as I didn't have access to those until I think much later.

Let me try the disks in various emulators as well to see whats the deal. For now lets just assume its the disks and not the emulators. Appologies for the time waste

**Comment by mras0** [comment]
@rhinoid I've found that the IPF version of the disk plays the music (in WinUAE atleast, vAmiga doesn't support that format). Other versions floating around on the internet (not claiming I've tried all of them) don't even enable audio DMA, so maybe some well spread crack caused that.

In other words, I think you're right that this is a disk issue and not a vAmiga problem.

**Comment by rhinoid** [comment]
Ok amazing. I was already at the point of complete bamboozlement.

I have 3 or 4 different disk images. One appears the original, and others have varying amount of cracktros in front of it. So I assumed they are probably based on some other version. However each and all of them didn't work. Which in my head sort off ruled out the 'faulty disk' hypothesis. But indeed, whatever emulator I throw at it, I never hear a peep in any of them, which rules out the 'faulty emulator' hypothesis. Which left me in the complete bamboozlement state.

Thanks for at least giving a small new lead.

I do have the original disks, so perhaps its up to me to somehow convert that to proper disks.

**Comment by mras0** [comment]
I now think I know what's going on. At first I didn't pay much attention to this sentence on the webpage:
>It also used a custom written disk loader (comparable to a floppy device driver nowadays) which was done to thwart potential disk copy programs. It used a specific way of encoding the data on disk so that it could be loaded, but not written.

Track 0 on the disks are normal amiga tracks in the usual format, but all other tracks are in a custom format. Haven't checked too much, but it uses a different syncword ($2291) rather than the usual $4489 and I don't think it uses "sectors" like a standard floppy, but just reads data in whole tracks. When the game was cracked/convert to standard disk format it probably didn't fit anymore, so they cut the intro music to make it fit.

If that's the only copy-protection, having the disks in extended ADF format should work with vAmiga(Web). I've tried two ways of making such disks:

1) Mounting the IPF disk in WinUAE and use XCopy to transfer the data to extended ADF files. This appears to create disks that work in WinUAE, but they seem to not work with vAmiga (my own build based on 2.2).
2) Hacking up a conversion tool based on the [IPF libraries](http://www.softpres.org/download). This does appear to work with vAmiga, but does not work with WinUAE?!

@dirkwhoffmann Not sure if you're interested in the extended ADF files that work with WinUAE but not vAmiga? With @rhinoid's permission I can share them with you. Maybe such a niche case isn't too worth the bother. Another thing I noticed in passing is that the retroshell doesn't support inserting `EXTFile`'s. `FloppyFile::make` is lacking
```
        case FILETYPE_EXT:  return new EXTFile(path);
```

@mithrendal Seems like vAmigaWeb doesn't support ext files, I've created an issue for that in vAmigaWeb (https://github.com/vAmigaWeb/vAmigaWeb/issues/141)

**Comment by dirkwhoffmann** [comment]
> @dirkwhoffmann Not sure if you're interested in the extended ADF files that work with WinUAE but not vAmiga? 

Yes, I am very interested in this disk. When I implemented EXTADF support in vAmiga, my biggest problem was the limited number of available test cases.

**Comment by rhinoid** [comment]
Of course you have my permission. I never saw any money from the publisher so we (the artist and musician as well) have seen it as public domain after we realised what scumbags they were.

Indeed can't remember the details of the top of my head with the copy protection. But indeed different syncword was one things which made copying a lot harder for casual xcopy people. Interesting hypothesis that they removed the music.

**Comment by rhinoid** [comment]
If at some point there is a working ADF, I would also be interested in it. Than I'll replace the version on Archive.org with it  ;^)

**Comment by dirkwhoffmann** [comment]
I think this issue can be closed as the IPF issue seems to be resolved (#769). Please reopen, if needed.
