### ISSUE TITLE
Using a folder as HDF

### ISSUE THREAD

**Issue by warpdesign** [dirkwhoffmann/vAmiga#798]
Would be great to have the ability to use a folder as harddisk.

I know it's possible to use a folder as ADF, but its size is very limited.

**Comment by dirkwhoffmann** [comment]
I just did a small code review to see how much work it would be. It's not as easy as I thought, because the current code only supports the conversion of directories to file systems with the size of floppy disks (the size cannot just be increased because directory blocks, bitmap blocks etc. must all reside at specific locations). 

Since utilities such as adftools already provide this functionality, I don't want to spend my own (limited) dev time on this project.
