### ISSUE TITLE
last line on workbench has always white color

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#818]
<img width="779" alt="IMG_7090" src="https://github.com/dirkwhoffmann/vAmiga/assets/17108995/7a6055d4-60cb-447f-b7aa-2a95fb8cfdae">

kickstart 1.2-1.3 
workbench 1.2
overscan
last line has white color

**Comment by dirkwhoffmann** [comment]
Not sure if it is a bug. I guess this line is never visible on a real monitor.

At least it's not a bug that was introduced recently. Even vAmiga 1.0.1 exhibited a white line (it looks different because that early version assembled the interlaced image differently):

<img width="1020" alt="Bildschirmfoto 2024-08-06 um 17 37 24" src="https://github.com/user-attachments/assets/c9e34c30-025a-408c-b5f9-53e07bfa62f0">
