### ISSUE TITLE
can’t use mouse in emulator on ipad

### ISSUE THREAD

**Issue by BobStadler** [dirkwhoffmann/vAmiga#830]
when i select mouse as game pad one i can move the pointer but not click.
i have a bluetooth mouse connected with my ipad.

**Comment by mithrendal** [comment]
Apples Magic Mouse secondary buttons is also working 😎 fine. 

It just has to be enabled in the iPadOS settings 

`general` => `trackpad and mouse` => `magic mouse` => `secondary click` = `right`

**Comment by BobStadler** [comment]
i am using a logitech mx master 3, this is the only mouse i have and i don’t have a usb to lightning adapter.

i already have turned that setting on, but no button works regardless

**Comment by mithrendal** [comment]
@BobStadler 
are you using vAmigaWeb ? Or vAmigaNet ? Or vAmiga for Mac via iPad screen sharing  ?

**Comment by BobStadler** [comment]
@mithrendal 
i am using vAmigaWeb.
today i couldn’t even move my mouse.

**Comment by mithrendal** [comment]
did you know ? there is also a dedicated github project page for [vAmigaWeb](https://github.com/vAmigaWeb/vAmigaWeb) for its specific issues 

lets check more details

which version of iPadOS, iPad are you on? 
can you control iPadOS with your mouse ? 
can you start vAmigaWeb from your HomeScreen by a mouse click ? 

whats the installed version of vAmigaWeb ? (you find version infos in the settings at the bottom)
below is the latest
<img width="362" alt="image" src="https://github.com/dirkwhoffmann/vAmiga/assets/17108995/e52c8248-8baf-4f62-b87d-5e96ea5353b3">

**Comment by BobStadler** [comment]
i can control ipad os fine with my mouse and i have vAmigaWeb on the desktop. 
i can also hover over elements in the emulator and click on the us elements o it.
if i chose the touch mouse option then i can even use that with my mouse. 
just the normal mouse option does not work inside the emulation. 
i updated and downgraded the version and tried both versions i have. 
i am running an iPad air 2 with IPadOS 15.8.2

**Comment by BobStadler** [comment]
thanks for giving me your time btw. @mithrendal

**Comment by mithrendal** [comment]
I am on iPadOs 17, I have unfortunately no iPadOS 15 device…

Then let’s test your device whether it supports the basic mouse events in safari which are used for mouse emulation in Amiga. E.g. `mousemove`, `mousedown` and `mouseup`

Here is the test web site
https://javascript.info/mouse-events-basics


Please test your mousedown/mouseup  like I did here in iPadOS17 
<img width="923" alt="image" src="https://github.com/dirkwhoffmann/vAmiga/assets/17108995/3511f96d-ab40-452b-b237-82949b77590f">


Please test mousemove like I did here
<img width="1000" alt="image" src="https://github.com/dirkwhoffmann/vAmiga/assets/17108995/15225cfb-4faf-4295-9995-ecf41a85e93a">

Is it working fine ?

**Comment by BobStadler** [comment]
i will test this as soon as i have my mouse back, sorry for the wait.

**Comment by BobStadler** [comment]
@mithrendal i have tested all of the things and they work.

**Comment by mithrendal** [comment]
ok good. its basically supported then.

now within vAmigaWeb create an `action button` with the following javascript

```javascript
remove_pointer_lock_fallback();
add_pointer_lock_fallback();
```

press your created action button and report whether mouse works

**Comment by mithrendal** [comment]
<img width="1366" alt="image" src="https://github.com/dirkwhoffmann/vAmiga/assets/17108995/016ee87d-3983-431a-9279-e887130e62d6">

**Comment by BobStadler** [comment]
hi, im back.

i tried it and it worked 50%, i can now move the cursor again. i uploaded a video of it to mega

https://www.mediafire.com/file/cpyoy9qvzl4aflj/IMG_2443.MOV/file

**Comment by BobStadler** [comment]
hi, sorry for beeing so late. there was a lot happening. and it is media fire not mega

**Comment by BobStadler** [comment]
i have added a mega link since i think one can stream the video then and doe sent need to download it.  
https://mega.nz/file/dPF1FRBD#IKPTTct7wpEpdftKbODZNdPyW-vGiN-xwxyBG9PPYUs

**Comment by BobStadler** [comment]
oh, and in there you can also see the weird things the mouse id doing like going really fast and not beeing integrated correctly.

**Comment by mithrendal** [comment]
I watched your video … I noticed that you enabled `assistive touch` and with it enabled I am able reproduce that left mouse button click is not working.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/fcce7329-f3bc-4d67-92f1-94af991a2030">

When I disable`assistive touch` left mouse button work again !!!
Seems as if assistive touch is hindering vAmigaWeb from processing the mouse buttons somehow.

BTW: a good test is the controller test of the Amiga test kit  https://github.com/keirf/amiga-stuff/releases

Can you please disable the assistive touch and report whether it works then ?
Nevertheless I will look in the coming days why vAmigaWeb is not receiving mouse click with the assistivetouch enabled.

Regarding the mouse speed you can adjust the speed of the mouse on the Amiga side via workbench preferences… 

Regarding not being integrated correctly … that is because iPadOS does not offer the so called html5 pointerlock API unfortunately. The current fallback is that you control two pointers at once …  one circle which belongs to the host OS i.e. your iPadOS and an the Amiga arrow icon. In the coming Releases of iPadOS that might change… when Apple changes this in the future then vAmigaWeb will detect it and offer the real integration i.e. only the Amiga mouse cursor will be visible then.

**Comment by mithrendal** [comment]
After some more investigation it becomes clear that vAmigaWeb support for physical mouse is not working correctly with Apples `Assistive Touch` feature being enabled. 

`Assistive Touch` does for example mimic an onscreen home button (in case your physical button is damaged or not working anymore).  IPadOS does not deliver correctly timed mouse events … and in some cases no mouse events at all … when this AssistiveTouch thing is enabled.

I discovered that it works well with the modern pointer event API, so the way here is to migrate the parts of code which still rely on mouse events to the modern pointer event API.

**Comment by mithrendal** [comment]
Now I got it… it is not the `assistive touch` feature in general what is hindering the mouse to work correctly.

It is the following setting which is enabled by default when assistive touch is turned on.

**Accessibility->AssistiveTouch->Perform Touch Gestures**

- _Simulate a finger when performing gestures with a pointing device._ 

 
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/b105dded-a65c-43f4-89dd-d832506f02a1">


What happens when this setting is enabled is that if you press the mouse button then iPadOS translates this into a finger touch event. vAmigaWeb thinks the user touched the screen … 😀 hence no mouse button click. 


If you need assistive touch because your home button is not working then you can use it. In order to use a mouse on iPad you have to turn off this finger touch simulation as it breaks the mouse button events.

**Comment by nicolasbauw** [comment]
> Regarding not being integrated correctly … that is because iPadOS does not offer the so called html5 pointerlock API unfortunately. The current fallback is that you control two pointers at once … one circle which belongs to the host OS i.e. your iPadOS and an the Amiga arrow icon. In the coming Releases of iPadOS that might change… when Apple changes this in the future then vAmigaWeb will detect it and offer the real integration i.e. only the Amiga mouse cursor will be visible then.

That would be great because this is a little annoying when playing a game like Dune with a bluetooth mouse. Even by adjusting mouse speed, the host cursor movement is never proportional to the emulator cursor.

**Comment by dirkwhoffmann** [comment]
Solved according to @mithrendal

**Comment by BobStadler** [comment]
thanks a lot, acctually what happened and why i couldnt respond anny more is because i switched to a chrome book and manny other things. maybe this will also help other people in the future!
thanks for all the help.
