### ISSUE TITLE
Emulation still uses CPU when paused

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#846]
3.0b2
I don't think that was the case with 2.6.2
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/efee3756-1f9a-424a-a4ed-ee3de486ba0f">

**Comment by dirkwhoffmann** [comment]
This is most likely because v3.0b2 was compiled as a debug build. 

Here is a comparison between v3.0 and v2.6.2 on my MacBook: 

vAmiga running at normal speed (v3.0 on top):

<img width="785" alt="Bildschirmfoto 2024-12-29 um 11 42 39" src="https://github.com/user-attachments/assets/94229036-52a6-4f1e-8bf0-25a20280dd8c" />

vAmiga paused (v3.0 on top):

<img width="785" alt="Bildschirmfoto 2024-12-29 um 11 42 17" src="https://github.com/user-attachments/assets/2739014d-6df7-4639-bc37-badbf2a52403" />

It's roughly the same.

**Comment by nicolasbauw** [comment]
OK, that was just me expecting the emulator to be idle when  the emulation is paused.
I guess you can close this one :-)
