### ISSUE TITLE
Support UAE callbacks from code

### ISSUE THREAD

**Issue by m0ppers** [dirkwhoffmann/vAmiga#848]
Not sure if this is really a good issue title.

UAE seems to be controllable from the amiga. namely the bartman toolchain offers 2 very nice C functions that interact with UAE:

KPrintF
and
warpmode

with KPrintf you can output debug information to the emulator and with warpmode you can enable and disable warpmode which is really helpful when developing.

Maybe it is easy to implement? Here is what the bartman toolchain is doing:

https://github.com/BartmanAbyss/vscode-amiga-debug/blob/master/template/support/gcc8_c_support.c

I am using 3.0.0b2

**Comment by dirkwhoffmann** [comment]
The vAmiga approach to communicating with the emulator from within the Amiga is by "connecting" RetroShell to the serial port. I've chosen this approach due to its flexibility, i.e., you have full access to all RetroShell commands.

You can connect to RetroShell by plugging the *Commander* into the serial port: 

<img width="640" alt="Bildschirmfoto 2024-12-02 um 11 48 38" src="https://github.com/user-attachments/assets/23d27fd3-961b-4804-9b39-e72a235a030e">

After that, you can control RetroShell from within the Amiga. E.g. to enable warp mode, you could do the following:

<img width="1019" alt="Bildschirmfoto 2024-12-02 um 11 53 14" src="https://github.com/user-attachments/assets/ccd3f9c9-9043-4b3c-9724-01e941b99859">

**Comment by m0ppers** [comment]
ok that should work! thanks for the info :)
