### ISSUE TITLE
selecting NTSC Agnus after reset behaves as PAL again

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#851]
1. set Agnus from PAL to NTSC
2. vAmiga switches to NTSC display
3. reset
4. vAmiga switches to PAL display
5. open hardware settings still shows NTSC selection, despite displaying PAL

should NTSC setting not survive a reset ?

**Comment by dirkwhoffmann** [comment]
Here is the thing: vAmiga has a config option named `OPT_VIDEO_FORMAT` which configures the Agnus chip. From ECS on, the Amiga can switch between  PAL and NTSC in its own by setting or clearing a specific bit in `BEAMCON0`.  Currently, vAmiga performs the switch, but does not alter the config option. Since this is confusing, we should allow the Amiga to change its own configuration in this case.

**Comment by dirkwhoffmann** [comment]
Fixed in v3.0
