### ISSUE TITLE
R-Type II sprite background error

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#86]
R-Type II intro does not work and after press LMB vAmiga hangs.

**Game:**
[R-Type II (1991)(Activision)[cr SKR][t +6 LGD].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3365409/R-Type.II.1991.Activision.cr.SKR.t.%2B6.LGD.adf.zip)

**Crash Report:**
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3365408/report.txt)

**Intro screen before pressing LMB:**
<img width="889" alt="Schermata 2019-07-07 alle 10 25 35" src="https://user-images.githubusercontent.com/34916641/60765918-ff9a6c80-a0a1-11e9-843a-7c8aec0b4e82.png">

**Comment by dirkwhoffmann** [comment]
vAmiga is improving slowly, but steadily...

<img width="920" alt="Screenshot 2019-07-09 at 17 23 46" src="https://user-images.githubusercontent.com/12561945/60902307-b1d35f00-a26f-11e9-9dc3-a8e2f7b8d16a.png">

At first I thought the remaining errors could be related to dual-playfield mode, but the Copper list shows that only a single playfield is used (5 bitplanes, lores).

<img width="1011" alt="Screenshot 2019-07-09 at 17 28 36" src="https://user-images.githubusercontent.com/12561945/60902448-ec3cfc00-a26f-11e9-9c41-c25a70086d84.png">

I expect that the remaining issues are due to color timing. The intro sets up a huge 2nd Copper list with color values that are modified dynamically by the CPU at the beginning of each frame. 

<img width="389" alt="Screenshot 2019-07-09 at 17 29 21" src="https://user-images.githubusercontent.com/12561945/60902586-20b0b800-a270-11e9-8149-b37817dd80fd.png">

Time to add some color timing tests to vAmigaTS...

**Comment by dirkwhoffmann** [comment]
Issue in the middle has been fixed (was a shift register issue that came up when the number of enabled bitplanes got reduced):

<img width="893" alt="Screenshot 2019-07-11 at 10 42 43" src="https://user-images.githubusercontent.com/12561945/61037575-a2692880-a3cb-11e9-9b70-65d6fc8debaf.png">

Remaining issue is a color problem in the ticker line at the bottom: 

Reference: 

<img width="746" alt="Screenshot 2019-07-11 at 10 44 32" src="https://user-images.githubusercontent.com/12561945/61037634-c3317e00-a3cb-11e9-81d2-f50675d2932e.png">

vAmiga: 

<img width="733" alt="Screenshot 2019-07-11 at 10 54 48" src="https://user-images.githubusercontent.com/12561945/61037672-d17f9a00-a3cb-11e9-9888-712f1a065033.png">

I expect Copper timing to get out of sync when switching over to the next scan line. 

TODO: Add a color test to vAmigaTS repo that lets Copper cross the HSYNC boundary.

**Comment by dirkwhoffmann** [comment]
Two issues identified: 

    [569] ( 96,212)  070020 BCB-D- 606C 0000 [0701FA] Copper: COPPC: 701FA move(COLOR00, $FFF) (4095)
    [569] ( 96,214)  070020 BCB-D- 606C 0000 [0701FA] Agnus: Copper blocked by bitplane DMA
    [569] ( 96,218)  070020 BCB-D- 606C 0000 [0701FE] Copper: COPPC: 701FE move(COLOR00, $4F4) (1268)
    [569] ( 96,222)  070020 BCB-D- 606C 0000 [070202] Copper: COPPC: 70202 move(COLOR00, $0) (0)
    [569] ( 96,226)  070020 BCB-D- 606C 0000 [070206] Copper: COPPC: 70206 move(COLOR00, $FFF) (4095)
    [569] ( 97,  3)  070020 BCB-D- 606C 0000 [07020A] Copper: COPPC: 7020A move(COLOR00, $4F4) (1268)
    [569] ( 97,  7)  070020 BCB-D- 606C 0000 [07020E] Copper: COPPC: 7020E move(COLOR00, $F00) (3840)

- Copper is granted  bus access in the last DMA cycle (226, $E2). It has to be denied. 
- When crossing the HSYNC boundary, Copper starts to use the odd DMA cycles which is totally wrong.

**Comment by dirkwhoffmann** [comment]
😎

<img width="893" alt="Screenshot 2019-07-11 at 12 19 24" src="https://user-images.githubusercontent.com/12561945/61043451-99ca1f80-a3d6-11e9-9e09-7740698f5cd5.png">

**Comment by dirkwhoffmann** [comment]
Let's see how this intro continues...

<img width="740" alt="Screenshot 2019-07-11 at 12 28 11" src="https://user-images.githubusercontent.com/12561945/61043843-8c616500-a3d7-11e9-94e9-4b230b6e77ba.png">

Oh no 🙈:

<img width="893" alt="Screenshot 2019-07-11 at 12 25 02" src="https://user-images.githubusercontent.com/12561945/61043856-94b9a000-a3d7-11e9-8bf6-cccd2cc89717.png">

**Comment by dirkwhoffmann** [comment]
Graphics error was due to a dual playfield bug. Now it rocks: 

<img width="893" alt="Screenshot 2019-07-17 at 13 08 21" src="https://user-images.githubusercontent.com/12561945/61371354-d2fe0600-a894-11e9-8347-0f5c3af7a3b0.png">

Time to bring the game on 😎... click ... damn 😖.

    Assertion failed: (isDue<REG_CPU_SLOT>(amiga->masterClock)), 
    function scheduleRegEvent, file EventHandler.cpp, line 832.

No need to panic though, I expected this to happen eventually. I need a more sophisticated REG_CPU_SLOT handler (which is responsible to delay register writes triggered by the CPU).

**Comment by dirkwhoffmann** [comment]
😎

<img width="893" alt="Screenshot 2019-07-17 at 14 21 57" src="https://user-images.githubusercontent.com/12561945/61375579-87048e80-a89f-11e9-9ab0-b6e9aebdc746.png">

<img width="849" alt="Screenshot 2019-07-17 at 14 40 45" src="https://user-images.githubusercontent.com/12561945/61376195-03e43800-a8a1-11e9-821f-503d5fd8c483.png">

<img width="893" alt="Screenshot 2019-07-17 at 14 40 51" src="https://user-images.githubusercontent.com/12561945/61376241-1c545280-a8a1-11e9-81b2-f639647a83fe.png">

There might be an issue with the CIAA shift register though (which is connected to the keyboard). The game queries the interrupt bit in CIAA::ICR explicitly and the game recognised a key press only when the key is held down for about half a second. TODO: Check if the IRQ bit gets deleted by the keyboard if a key is released.

**Comment by dirkwhoffmann** [comment]
Keyboard issue is fixed (was a subtle bug in CIA::peek() that also affects VirtualC64). 

If somebody wants to give R-Type II a try in vAmiga, please download the latest alpha version:

http://www.dirkwhoffmann.de/vAmiga/vAmiga_0.29.zip

It's playable until the cave (or spaceship?) comes up... this is where graphics glitches begin to appear...

<img width="893" alt="Screenshot 2019-07-17 at 15 20 25" src="https://user-images.githubusercontent.com/12561945/61380071-02b70900-a8a9-11e9-8f17-335c4ab6cb8e.png">

**Comment by dirkwhoffmann** [comment]
The DMA inspector shows sprite activity exactly in those line where the graphics errors happen.

<img width="893" alt="Bildschirmfoto 2019-07-22 um 16 09 11" src="https://user-images.githubusercontent.com/12561945/61639386-ab93a880-ac9b-11e9-989d-8c9e2665ffc6.png">

I therefore conclude that the dark erroneous parts are sprites and they are supposed to be there. They are just not supposed to be in the foreground, but in the background. vAmiga always draws sprites in the foreground at the moment 🙄.

I guess the issue goes away once the sprite code has been refined.

BTW, this game is the winner w.r.t. DMA activity (Copper is on fire 🤯).

**Comment by dirkwhoffmann** [comment]
Intro is broken in the current built: 

<img width="893" alt="Bildschirmfoto 2019-08-01 um 14 43 17" src="https://user-images.githubusercontent.com/12561945/62294286-e0a5b500-b46a-11e9-82bb-b194ccbaef30.png">

Last verified working version: V029.1

**Comment by dirkwhoffmann** [comment]
Intro broke with commit 05bb30b. It's working again. 

Still working on sprite / bitplane priorities. It turned out to be harder than expected, because I need to rework vAmiga's graphics pipeline (again). The former 2-pass process had to be replaced my 3-pass process: 

- Pass 1: Capture bitplane data 

- Pass 2: Translate bitplane data to color register indices and build a zBuffer.
 
  Translation is needed for dual-playfield mode, z buffering is needed for proper sprite handling.

- Pass 3: Translate the result into RGBA values and write them into the screen buffer that is later read by the GPU.

Pass 1 is done  by Agnus during emulation. Pass 2 and pass 3 are performed by Denise in the hSync handler.

**Comment by dirkwhoffmann** [comment]
With the new z buffer, it's now possible to draw sprites in the background. 

<img width="138" alt="Bildschirmfoto 2019-08-02 um 13 28 24" src="https://user-images.githubusercontent.com/12561945/62367311-8ae41200-b529-11e9-8970-95f2c92a6c7a.png">

TODO: Add some sprite tests to vAmigaTS repo.

**Comment by dirkwhoffmann** [comment]
Now it looks like this (haven't verified yet how it is supposed to look): 

<img width="893" alt="Bildschirmfoto 2019-08-02 um 13 42 45" src="https://user-images.githubusercontent.com/12561945/62368103-e57e6d80-b52b-11e9-856d-988df662accb.png">

**Comment by dirkwhoffmann** [comment]
Just played it on the real device 😎. The darker background image is supposed to be there and it's really supposed to look like in vAmiga. On a real Amiga, however, it spans over the whole screen. 

Strange enough: A sprite consists of 16 lores pixels. Hence, it's only possible to cover a maximum of 8 * 16 = 128 lores pixels with sprites. How can the background be filled completely then? 🤔

Need to play the game a little further. Unfortunately, I usually get killed before reaching the interior of the space ship.

**Comment by Alessandro1970** [comment]
Now the intro works, this can be closed.

**Comment by dirkwhoffmann** [comment]
R-Type II uses horizontal sprite multiplexing as explained here: 

https://codetapper.com/amiga/sprite-tricks/r-type-2/

Now it's perfectly clear why vAmiga doesn't draw the background correctly. Need to think about an efficient solution how to implement this...

**Comment by dirkwhoffmann** [comment]
Horizontal sprite multiplexing in action 😎:

<img width="814" alt="Bildschirmfoto 2019-10-11 um 10 32 40" src="https://user-images.githubusercontent.com/12561945/66637764-f88c7880-ec13-11e9-8b2f-ddaab831dd07.png">
